### ISSUE TITLE
什么时候支持typescript?

### ISSUE THREAD

**Issue by amangqq** [yangzongzhuan/RuoYi-Vue3#101]

**Comment by huangwenboha563** [comment]
typescript确实是趋势，但是会给前端带来心智负担，小项目用处不大，估计作者下个大版本会支持ts的。

**Comment by YFengFly** [comment]
ts已经有类似模板了，比如 https://vvbin.cn/doc-next/
本来我也十分希望用 ts，奈何团队用不起来，只好作罢，选择了现在不用 ts 的若依
主要还是看若依打算面向什么样的用户群，对于小团队、小项目，ts 不太容易推行
如果是大团队，他们会直接用若依...?
如果出不同的 js、ts 版本，维护成本又很高...emm...不是太容易平衡的问题

**Comment by huangwenboha563** [comment]
> ts已经有类似模板了，比如 https://vvbin.cn/doc-next/ 本来我也十分希望用 ts，奈何团队用不起来，只好作罢，选择了现在不用 ts 的若依 主要还是看若依打算面向什么样的用户群，对于小团队、小项目，ts 不太容易推行 如果是大团队，他们会直接用若依...? 如果出不同的 js、ts 版本，维护成本又很高...emm...不是太容易平衡的问题

vben 都说ts封装过度 哈哈
