### ISSUE TITLE
部署前端项目出现了Failed to load module script:  Expected a JavaScript module script but the server responded with a MIME type of "text/plain".  Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by ZHChan-2019** [yangzongzhuan/RuoYi-Vue3#103]
部署前端项目出现了Failed to load module script:  Expected a JavaScript module script but the server responded with a MIME type of "text/plain".  Strict MIME type checking is enforced for module scripts per HTML spec.这个错误，查了很多资料都没有办法解决

**Comment by ZHChan-2019** [comment]
nginx路径都配置没有问题，可是就是出现了这个问题

**Comment by HHDaddy** [comment]
遇到类似的问题，搞不定。Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". strict MIMe type checking is enforced for module scripts per HTPL spec.
Typerror: Failed to fetch dynamiclly imported module: 
部署正常，当时访问页面静置一段时间会出现

**Comment by lzc-2019** [comment]
有解决方法了么

**Comment by yangzongzhuan** [comment]
项目技术相关的问题请到 https://gitee.com/y_project/RuoYi-Vue/issues 提问，同时提供出能复现问题步骤。
