### ISSUE TITLE
用户列表页面,后端没有查询部门的接口呀

### ISSUE THREAD

**Issue by lzc-2019** [yangzongzhuan/RuoYi-Vue3#106]

**Comment by eoc2015** [comment]
自己启一个后端项目就行了，v3和v2通用的

**Comment by lzc-2019** [comment]
> 



> 自己启一个后端项目就行了，v3和v2通用的

是3.8.4版本少了一些接口,但是页面还在.这些接口不知道出于什么原因删掉了,我在3.8.3的版本里面找到了对应接口
