### ISSUE TITLE
菜单切换会出现空白问题

### ISSUE THREAD

**Issue by alaxury** [yangzongzhuan/RuoYi-Vue3#111]
版本vue3,  刷新变正常，dev环境，还没上生产
【不传不了图片耶】
【百度到了个类似的https://gitee.com/y_project/RuoYi-Vue/issues/I5F40M】
不是说修复了么，咋又出现了。

**Comment by yangzongzhuan** [comment]
项目技术相关的问题请到 https://gitee.com/y_project/RuoYi-Vue/issues 提问，同时提供出能复现问题步骤。

**Comment by Fxiao1** [comment]
在这个[issue](https://gitee.com/y_project/RuoYi-Vue/issues/I5F40M)中找到解决办法了，跟着作者的提示排查。果然是我`<template>`根目录下多了个一个标签，即：

```html
<template>
  <!-- region -->
  <div class="app-container">
  ……
```

正确的应改成

```html
<template>
  <div class="app-container">
  <!-- region -->
  ……
```

检查下，看看你的是不是也存在这样的问题
