### ISSUE TITLE
为什么页面中直接可以使用onMounted，watch等，不需要import { onMounted, watch} from "vue"引入

### ISSUE THREAD

**Issue by weijianpeng18421** [yangzongzhuan/RuoYi-Vue3#115]
![image](https://user-images.githubusercontent.com/29622256/202325348-1d680f62-14c4-4b64-bd06-63fcebc2d52d.png)

**Comment by yangzongzhuan** [comment]
因为项目有依赖vue3自动引入插件 unplugin-auto-import

**Comment by weijianpeng18421** [comment]
感谢大佬
