### ISSUE TITLE
貌似跑不起来呀 大佬

### ISSUE THREAD

**Issue by hjzg** [yangzongzhuan/RuoYi-Vue3#116]

**Comment by yangzongzhuan** [comment]
测试是能正常运行的，你可以提供相关错误截图出来看看？

**Comment by XiaZhi246430** [comment]
![1670220558806](https://user-images.githubusercontent.com/23652732/205561698-e7416fbc-4baf-4485-b911-ecad266b0929.png)

**Comment by yangzongzhuan** [comment]
错误很明显了，80端口你没有权限，你可以改一下端口为其他的数字在启动试试。
