### ISSUE TITLE
TagsView 关闭active的tag 页面不执行onBeforeUnmount&onUnmounted，关闭非actvie的tag才执行

### ISSUE THREAD

**Issue by beckding** [yangzongzhuan/RuoYi-Vue3#127]
keepalive的页面，关闭active的tag 页面执行  onBeforeUpdate、onUpdated、onDeactivated
不执行onBeforeUnmount&onUnmounted，关闭非actvie的tag执行onBeforeUnmount&onUnmounted
如何才能在关闭active的tag 页面时执行onBeforeUnmount&onUnmounted
![image](https://user-images.githubusercontent.com/34854755/210742555-daec11ac-04a6-410d-8a4c-8c6fa67bdf97.png)
![image](https://user-images.githubusercontent.com/34854755/210742817-e588b4e0-d18f-465d-90dd-85930932c8a1.png)

**Comment by ceuer** [comment]
同问

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
