### ISSUE TITLE
请问 vue3 什么时候能加上 表单构建功能呢？

### ISSUE THREAD

**Issue by gantoday** [yangzongzhuan/RuoYi-Vue3#128]
![image](https://user-images.githubusercontent.com/7780154/211279053-c4cd0b0f-786a-4b3a-be01-5f4b1e6b0fa5.png)

发现表单构建还是空的。有规划这个功能什么时候能做吗？

程序很棒。非常感谢。

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues

**Comment by gantoday** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我成功收到了你的邮件！
