### ISSUE TITLE
项目发布到线上后第一次加载打开收屏超级慢，大概需要6秒钟的加载，看能否解决优化一下

### ISSUE THREAD

**Issue by heimanba-ct** [yangzongzhuan/RuoYi-Vue3#133]
项目发布到线上后第一次加载打开收屏超级慢，大概需要6秒钟的加载，看能否解决优化一下

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
