### ISSUE TITLE
关于v3.8.5三级菜单打开页面时第二次打开及后续打开都会出现空白问题

### ISSUE THREAD

**Issue by xmt2018** [yangzongzhuan/RuoYi-Vue3#136]
v3.8.4的版本时接口返回的路由数据生成的三级菜单打开正常，但v3.8.5以后发现相同的返回数据生成的三级菜单只能在第一次打开时正常，第二在打开就会出现页面空白的现像，如下图
![image](https://user-images.githubusercontent.com/39377636/219302924-dc0b995e-a82b-400e-b609-0fc2e88bad82.png)
在次点击其它菜单时就会出现页面空白，在切其它菜单时还是一样
![image](https://user-images.githubusercontent.com/39377636/219303253-fe0e648d-64a4-482a-97fb-545a751a235f.png)
但路由对应的页面地址肯定是对的，而且测试了二级菜单的情况又是正常的
![image](https://user-images.githubusercontent.com/39377636/219304054-91a4ca8b-3b96-4450-a8d0-9d30c9387e1b.png)
想请大佬百忙中抽个空帮忙看下，感谢感谢

**Comment by myma911** [comment]
请大佬百忙中抽个空帮忙看下，感谢感谢

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
