### ISSUE TITLE
请问下大家 RuoYi-Vue3 里面是 Vue3，能直接结合 RuoYi-Cloud 里的后台直接用 吗？

### ISSUE THREAD

**Issue by delbug** [yangzongzhuan/RuoYi-Vue3#139]
请问下大家 RuoYi-Vue3 里面是 Vue3，能直接结合 RuoYi-Cloud 里的后台直接用 吗？
<img width="925" alt="image" src="https://user-images.githubusercontent.com/47682158/220816173-8aea7533-acea-416d-977e-ce7d1bd95fb7.png">

**Comment by yujiayinshi** [comment]
同问，下载RuoYi-Cloud，能够正常运行，然后再运行RuoYi-Vue3，发现各种接口对不上。

**Comment by scipioam** [comment]
RuoYi-Vue的vue3前端是对应了这个仓库（RuoYi-Vue3）
RuoYi-Cloud的vue3前端是对应了另一个仓库：RuoYi-Cloud-Vue3

**Comment by yangzongzhuan** [comment]
微服务下载 https://github.com/yangzongzhuan/RuoYi-Cloud-Vue3
