### ISSUE TITLE
请问这个和Ruoyi-could-vue3有什么区别？

### ISSUE THREAD

**Issue by liweiook** [yangzongzhuan/RuoYi-Vue3#14]

**Comment by liweiook** [comment]
因为我的项目是vue2版本的ruoyi，近期打算升级为vue3应该看哪个库呢？

**Comment by baiban114** [comment]
我看了下，Cloud版本的后端接口有些不一样，用这个版本连接cloud后端会报404

**Comment by yangzongzhuan** [comment]
稍许接口不一样，其他的都一致。

**Comment by maqingbo** [comment]
我把两个项目都克隆到本地对比了一下，左侧 Ruoyi-vue3，右侧 Ruoyi-could-vue3。

各自独有的文件：

<img width="1265" alt="Snipaste_2022-07-15_18-23-19" src="https://user-images.githubusercontent.com/20136852/179205877-04e5ac44-2174-4432-a670-c4a0e4202c72.png">

文件名称一致，内容有差异的只有一个文件：   

<img width="1265" alt="Snipaste_2022-07-15_18-22-16" src="https://user-images.githubusercontent.com/20136852/179205605-6f72e7be-2a4f-4404-9064-8d7a81955c8b.png">

<img width="1244" alt="Snipaste_2022-07-15_18-18-55" src="https://user-images.githubusercontent.com/20136852/179205855-81cd8c5e-b42f-4259-a716-4e42c5a1ab3c.png">
