### ISSUE TITLE
点击tab上的叉号关闭页面或者右键选择关闭，不会触发onUnmounted钩子

### ISSUE THREAD

**Issue by Amaoone** [yangzongzhuan/RuoYi-Vue3#143]
![1678787204660](https://user-images.githubusercontent.com/116626855/224961833-e13b26c7-475d-40f1-9f07-41104e60b10f.jpg)
红圈的选项都不会触发，绿圈的会触发

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
