### ISSUE TITLE
麻烦开发依赖包 vite 更新到官网的4.2.0版本

### ISSUE THREAD

**Issue by dong-lufei** [yangzongzhuan/RuoYi-Vue3#144]
麻烦开发依赖包 vite 更新到官网的4.2.0版本，升级后我再用

**Comment by dong-lufei** [comment]
还有生产依赖包 axios 版本可以升到1点几的版本哦

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
