### ISSUE TITLE
系统接口500异常

### ISSUE THREAD

**Issue by YouthguyZ** [yangzongzhuan/RuoYi-Vue3#146]
前两天还可以正常启动展示页面，怎么突然运行 打开地址就会报系统接口500异常 getInfo logout 接口都是500状态码

**Comment by ihoment-chenzexin** [comment]
![image](https://user-images.githubusercontent.com/75963620/236361829-332b0174-4495-4b0d-93d3-fbd46f72bef9.png)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
