### ISSUE TITLE
代码生成，使用字典值时，vue页面错误

### ISSUE THREAD

**Issue by Asenlen** [yangzongzhuan/RuoYi-Vue3#149]
使用vue3代码，在生成代码时，给需要设置的字段选择下拉框，并且选择字典sys_normal_disable，但是生成的vue页面的字典会有dict.type.sys_normal_disable，页面报错打开是空白

**Comment by Asenlen** [comment]
请问下这个问题应该如何修改

**Comment by wasonCheung** [comment]
搞定了码 ，我也遇到这个问题了

**Comment by wasonCheung** [comment]
搞定了 ，参考system/user的方式

**Comment by Asenlen** [comment]
感谢感谢

**Comment by wqiuming** [comment]
不用改，应该是你们生成的模板还是用的v2的模板，替换v3模板重新生成v3代码即可。
![微信图片_20230728003524](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/29088495/ef3e02ce-5aaa-41c4-887a-0a948b9cdabd)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues

**Comment by wqiuming** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
