### ISSUE TITLE
若依 和 芋道有啥区别，是不同家的吗

### ISSUE THREAD

**Issue by 5201314999** [yangzongzhuan/RuoYi-Vue3#150]

**Comment by yangzongzhuan** [comment]
嗯，不同家，芋道是基于若依项目去做的额外扩展，你有兴趣也可以自己扩展后加入进来。
http://doc.ruoyi.vip/ruoyi-vue/document/xmkz.html

**Comment by zjutjsj1004** [comment]
> 嗯，不同家，芋道是基于若依项目去做的额外扩展，你有兴趣也可以自己扩展后加入进来。 http://doc.ruoyi.vip/ruoyi-vue/document/xmkz.html

那我们开发项目是使用ruoyi 还是  ruoyi-pro
