### ISSUE TITLE
关于自动生成的模板，图标失效和字典失效的解决办法

### ISSUE THREAD

**Issue by wasonCheung** [yangzongzhuan/RuoYi-Vue3#153]
`  <el-option
              v-for="(dict,index) in pa_video_status"
              :key="index"
              :label="dict.label"
              :value="dict.value"
          />`

`   pa_video_status: this.useDict('pa_video_status')['pa_video_status']`

图标的问题 去掉前缀就好了

icon="el-icon-Plus" =>>> icon="plus"

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
