### ISSUE TITLE
长时间没点击路由菜单 再点击就没有内容 页面空白 要怎么解决 

### ISSUE THREAD

**Issue by 2245573029** [yangzongzhuan/RuoYi-Vue3#154]
我自己处理的话是在根组件加上 key 但是key 在点击路由菜单的时候会有回弹效果 体验不是很好 还有在有些地方会出现 bug
有好的解决方法嘛

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。

**Comment by Fxiao1** [comment]
在这个[issue](https://gitee.com/y_project/RuoYi-Vue/issues/I5F40M)中找到解决办法了，跟着作者的提示排查。果然是我`<template>`根目录下多了个一个标签，即：

```html
<template>
  <!-- region -->
  <div class="app-container">
  ……
```

正确的应改成

```html
<template>
  <div class="app-container">
  <!-- region -->
  ……
```

检查下，看看你的是不是也存在这样的问题
