### ISSUE TITLE
cityCode传值""，会被忽略掉

### ISSUE THREAD

**Issue by JUNPENG1992** [yangzongzhuan/RuoYi-Vue3#155]
接口请求传值cityCode:""需要返回所有城市的数据，现在这样传值参数会被忽略掉

![image](https://user-images.githubusercontent.com/12162565/230559182-c7b2b8e4-f767-4f9f-9405-75564d968393.png)

不知去掉标红这块代码，是否对整体有影响。

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
