### ISSUE TITLE
settings.js 中关闭tagsView会造成开发时热更新页面空白，组件不显示

### ISSUE THREAD

**Issue by spadek-w** [yangzongzhuan/RuoYi-Vue3#156]
## 过程
settings.js 中tagsView 改为false
```
{
...
 /**
   * 是否显示 tagsView
   */
  tagsView: false,
...
}
```
## 产生的bug
在任意.vue文件的script中书写代码，比如换行、添加console。
vite 热更新后点击其他页面 路由跳转了，但是页面为空白。

> 建议settings.js 中tagsView 为false时, 
>/src/layout/components/AppMain.vue  应该不用keep-alive
> 可能不是最优，期待更新

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
