### ISSUE TITLE
在一个页面中import 另外一个界面 渲染一次问题

### ISSUE THREAD

**Issue by lztbwlkj** [yangzongzhuan/RuoYi-Vue3#159]
两个页面A.vue和B.vue 基本完全一致，只有部分请求参数不一致；
我先完成一个A.vue界面的内容，暴露出Props对应属性，再到B.vue中import A from "../A.vue"；
回到Web页面，来回点击A.vue和B.vue对应的菜单，会导致所有的页面只渲染一次，是所有的。后面就变空白页面

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
