### ISSUE TITLE
为什么el-dialog中的el-select关掉再打开选项就置空了呢？

### ISSUE THREAD

**Issue by JFDTTTT** [yangzongzhuan/RuoYi-Vue3#16]
问题：系统管理>菜单管理  点击任意一项修改，关掉dialog再次点击修改，select中的选项就为空了

**Comment by jian-jiu** [comment]
我也遇见了一样的问题，发现第一次dialog的z-index为2011，select为2014，可以正常显示，第二次dialog重新打开z-index就增加变成2016了，select还是2014，select被覆盖了。显示不出来。请问你已经解决了吗，可以告知方法吗

**Comment by zhuhaobam** [comment]
在dialog里面加上v-if="open"就好了，每次重新去接口重新拉取数据渲染。利用的v-if重新渲染的特性。
我还改造成了异步加载，异步回显。

**Comment by zhuhaobam** [comment]
`<template>
  <div class="el-tree-select">
    <el-select
      style="width: 100%"
      v-model="valueId"
      ref="treeSelect"
      :filterable="true"
      :clearable="clearable"
      :disabled="disabled"
      @clear="clearHandle"
      :filter-method="selectFilterData"
      :placeholder="placeholder"
    >
      <el-option :value="valueId" :label="valueTitle">
        <el-tree
          id="tree-option"
          ref="selectTree"
          :load="loadNode"
          :lazy="lazy"
          :accordion="accordion"
          :data="options"
          :props="objMap"
          :node-key="objMap.value"
          :expand-on-click-node="false"
          :default-expanded-keys="defaultExpandedKey"
          :filter-node-method="filterNode"
          @node-click="handleNodeClick"
        ></el-tree>
      </el-option>
    </el-select>
  </div>
</template>

<script setup>
const { proxy } = getCurrentInstance();

const props = defineProps({
  /* 配置项 */
  objMap: {
    type: Object,
    default: () => {
      return {
        value: "id", // ID字段名
        label: "label", // 显示名称
        children: "children", // 子级字段名
      };
    },
  },
  /* 自动收起 */
  accordion: {
    type: Boolean,
    default: () => {
      return false;
    },
  },
  /**当前双向数据绑定的值 */
  value: {
    type: [String, Number],
    default: "",
  },
  /**当前的数据 */
  options: {
    type: Array,
    default: () => [],
  },
  /**清除 */
  clearable: {
    type: Boolean,
    default: true,
  },
  /**不可编辑 */
  disabled: {
    type: Boolean,
    default: false,
  },
  /**懒加载 */
  lazy: {
    type: Boolean,
    default: false,
  },
  /**输入框内部的文字 */
  placeholder: {
    type: String,
    default: "",
  },
});

const emit = defineEmits([
  "update:value",
  "load:node",
  "click:node",
  "change:node",
]);

const valueId = computed({
  get: () => props.value,
  set: (val) => {
    emit("update:value", val);
  },
});
const valueTitle = ref("");
const watchNode = ref(null);
const defaultExpandedKey = ref([]);

function loadNode(node, resolve) {
  emit("load:node", node, (val, showData) => {
    resolve(val);
    const regionParentCode = showData.regionParentCode || "";
    const regionParentName = showData.regionParentName || "";
    if (regionParentCode.length > 0 && regionParentName.length > 0) {
      const regionParentCodeArray = regionParentCode.split(",");
      const regionParentNameArray = regionParentName.split(",");
      const booA = regionParentCodeArray.length > showData.level;
      const booB = regionParentCodeArray.length !== showData.level + 1;
      const booC = regionParentCodeArray.length === showData.level + 1;
      if (booA && booB) {
        const defaultKey = parseInt(regionParentCodeArray[showData.level]);
        defaultExpandedKey.value = [defaultKey];
      }
      if (booA && booC) {
        const defaultKey = parseInt(regionParentCodeArray[showData.level]);
        const defaultName = parseInt(regionParentNameArray[showData.level]);
        watchNode.value = {
          areaCode: defaultKey,
          areaName: defaultName,
        };
      }
    }
  });
}

function initHandle() {
  nextTick(() => {
    const selectedValue = valueId.value;
    if (
      selectedValue &&
      selectedValue !== null &&
      typeof selectedValue !== "undefined"
    ) {
      const node = proxy.$refs.selectTree.getNode(selectedValue);
      if (node) {
        emit("change:node", node.data);
        valueTitle.value = node.data[props.objMap.label];
        proxy.$refs.selectTree.setCurrentKey(selectedValue); // 设置默认选中
        defaultExpandedKey.value = [selectedValue]; // 设置默认展开
      }
    } else {
      clearHandle();
    }
  });
}

function handleNodeClick(node) {
  const nodeInfo = proxy.$refs.selectTree.getNode(node.areaCode);
  emit("click:node", nodeInfo);
  valueTitle.value = node[props.objMap.label];
  valueId.value = node[props.objMap.value];
  defaultExpandedKey.value = [];
  proxy.$refs.treeSelect.blur();
  selectFilterData("");
}
function selectFilterData(val) {
  proxy.$refs.selectTree.filter(val);
}
function filterNode(value, data) {
  if (!value) return true;
  return data[props.objMap["label"]].indexOf(value) !== -1;
}
function clearHandle() {
  valueTitle.value = "";
  valueId.value = "";
  defaultExpandedKey.value = [];
  clearSelected();
}
function clearSelected() {
  const allNode = document.querySelectorAll("#tree-option .el-tree-node");
  allNode.forEach((element) => element.classList.remove("is-current"));
}

onMounted(() => {
  initHandle();
});

watch(valueId, () => {
  initHandle();
});
watch(watchNode, () => {
  initHandle();
});
</script>

<style lang='scss' scoped>
@import "@/assets/styles/variables.module.scss";
.el-scrollbar .el-scrollbar__view .el-select-dropdown__item {
  padding: 0;
  background-color: #fff;
  height: auto;
}

.el-select-dropdown__item.selected {
  font-weight: normal;
}

ul li .el-tree .el-tree-node__content {
  height: auto;
  padding: 0 20px;
  box-sizing: border-box;
}

:deep(.el-tree-node__content:hover),
:deep(.el-tree-node__content:active),
:deep(.is-current > div:first-child),
:deep(.el-tree-node__content:focus) {
  background-color: mix(#fff, $--color-primary, 90%);
  color: $--color-primary;
}
:deep(.el-select) {
  width: 100%;
}
</style>`

**Comment by zhuhaobam** [comment]
`<el-form-item label="行政地区" prop="regionAreaCode">
              <tree-select
                style="width: 100%"
                v-model:value="form.regionAreaCode"
                @load:node="loadNode"
                @click:node="handleNodeClick"
                :lazy="true"
                :clearable="false"
                :objMap="{
                  value: 'areaCode',
                  label: 'name',
                  children: 'children',
                  isLeaf: 'isLeaf',
                }"
                placeholder="选择所属地区"
              />
            </el-form-item>`


`/** 行政地区懒加载 */
async function loadNode(node, resolve) {
  if (node.level === 0) {
    return resolve(
      [
        {
          areaCode: 0,
          level: null,
          name: "顶级节点（国家）",
          children: [],
          isLeaf: false,
        },
      ],
      {
        level: node.level,
        regionParentCode: form.value.regionParentCode,
        regionParentName: form.value.regionParentName,
      }
    );
  } else {
    const level = node.level === 1 ? 0 : node.level - 1;
    const areaCode = node.level === 1 ? 0 : node.data.areaCode || 0;
    await selectRegion({
      level: level,
      parentCode: areaCode,
    }).then((response) => {
      return resolve(
        proxy.handleTree(
          response.data.map((item) => {
            item.isLeaf = item.level > 3;
            item.children = [];
            return item;
          }),
          "areaCode"
        ),
        {
          level: node.level,
          regionParentCode: form.value.regionParentCode,
          regionParentName: form.value.regionParentName,
        }
      );
    });
  }
}`


下面是要将数据选中时存储方便回显
eg:
![image](https://user-images.githubusercontent.com/15319171/154183576-b37161d7-5f0e-4ade-bba3-216151383063.png)

![image](https://user-images.githubusercontent.com/15319171/154183455-e0a36ae2-dbee-4fbe-8f4f-4a666cd5cb71.png)

所使用的数据来源
https://github.com/kakuilan/china_area_mysql
查询你需要的
 <sql id="selectRegionVo">
        select level, parent_code, area_code, name
        from sys_region
    </sql>
![image](https://user-images.githubusercontent.com/15319171/154183971-0d494318-8a75-4f7f-9332-b4e3255768e4.png)


`/**将行政地区的所有上级和本级制成字符串 */
function loopParentAreaCode(nodeInfo, areas) {
  areas.unshift(nodeInfo.data.areaCode);
  if (nodeInfo.level > 1) {
    return loopParentAreaCode(nodeInfo.parent, areas);
  }
  return areas;
}

function loopParentAreaName(nodeInfo, areas) {
  areas.unshift(nodeInfo.data.name);
  if (nodeInfo.level > 1) {
    return loopParentAreaName(nodeInfo.parent, areas);
  }
  return areas;
}

function handleNodeClick(nodeInfo) {
  form.value.regionParentCode = loopParentAreaCode(nodeInfo, []).join(",");
  form.value.regionParentName = loopParentAreaName(nodeInfo, []).join(",");
}`

**Comment by JFDTTTT** [comment]
> 我也遇见了一样的问题，发现第一次dialog的z-index为2011，select为2014，可以正常显示，第二次dialog重新打开z-index就增加变成2016了，select还是2014，select被覆盖了。显示不出来。请问你已经解决了吗，可以告知方法吗
> 
> I also encountered the same problem, found the first dialog Z-index for 2011, select for 2014, can be displayed normally, the second time to open z-index will be increased to 2016, select or 2014, was overwritten. It's not showing. Have you solved it? Can you tell me how

没有解决，如果已定位了是css的问题，可以覆盖掉dialog第二次打开的z-index，但是不知道会不会引起其他的样式问题，可以试一下

**Comment by JFDTTTT** [comment]
> `<el-form-item label="行政地区" prop="regionAreaCode"> <tree-select style="width: 100%" v-model:value="form.regionAreaCode" @load:node="loadNode" @click:node="handleNodeClick" :lazy="true" :clearable="false" :objMap="{ value: 'areaCode', label: 'name', children: 'children', isLeaf: 'isLeaf', }" placeholder="选择所属地区" /> </el-form-item>`
> 
> `/** 行政地区懒加载 */ async function loadNode(node, resolve) { if (node.level === 0) { return resolve( [ { areaCode: 0, level: null, name: "顶级节点（国家）", children: [], isLeaf: false, }, ], { level: node.level, regionParentCode: form.value.regionParentCode, regionParentName: form.value.regionParentName, } ); } else { const level = node.level === 1 ? 0 : node.level - 1; const areaCode = node.level === 1 ? 0 : node.data.areaCode || 0; await selectRegion({ level: level, parentCode: areaCode, }).then((response) => { return resolve( proxy.handleTree( response.data.map((item) => { item.isLeaf = item.level > 3; item.children = []; return item; }), "areaCode" ), { level: node.level, regionParentCode: form.value.regionParentCode, regionParentName: form.value.regionParentName, } ); }); } }`
> 
> 下面是要将数据选中时存储方便回显 eg: ![image](https://user-images.githubusercontent.com/15319171/154183576-b37161d7-5f0e-4ade-bba3-216151383063.png)
> 
> ![image](https://user-images.githubusercontent.com/15319171/154183455-e0a36ae2-dbee-4fbe-8f4f-4a666cd5cb71.png)
> 
> 所使用的数据来源 https://github.com/kakuilan/china_area_mysql 查询你需要的 select level, parent_code, area_code, name from sys_region ![image](https://user-images.githubusercontent.com/15319171/154183971-0d494318-8a75-4f7f-9332-b4e3255768e4.png)
> 
> `/**将行政地区的所有上级和本级制成字符串 */ function loopParentAreaCode(nodeInfo, areas) { areas.unshift(nodeInfo.data.areaCode); if (nodeInfo.level > 1) { return loopParentAreaCode(nodeInfo.parent, areas); } return areas; }
> 
> function loopParentAreaName(nodeInfo, areas) { areas.unshift(nodeInfo.data.name); if (nodeInfo.level > 1) { return loopParentAreaName(nodeInfo.parent, areas); } return areas; }
> 
> function handleNodeClick(nodeInfo) { form.value.regionParentCode = loopParentAreaCode(nodeInfo, []).join(","); form.value.regionParentName = loopParentAreaName(nodeInfo, []).join(","); }`

👍🏻

**Comment by yangzongzhuan** [comment]
这个已经修复过了，需要升级版本到最新。
