### ISSUE TITLE
进入个人中心页面卡死问题

### ISSUE THREAD

**Issue by hutian13999** [yangzongzhuan/RuoYi-Vue3#161]
发现当进入个人中心时候页面卡死，发现<userAvatar :user="state.user" /> 向子组件(用户头像组件)传递了参数，但子组件并没有去defineProps接收这个参数，子组件不会对这个参数进行处理，但是在页面渲染时仍然会尝试去解析这个参数，可能会导致页面卡死了

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
