### ISSUE TITLE
全局layOut添加el-scrollbar组件之后,scroll-to.js滚动实效

### ISSUE THREAD

**Issue by 450929318** [yangzongzhuan/RuoYi-Vue3#162]
![image](https://user-images.githubusercontent.com/39305007/234757872-51f755e4-1274-413d-a04a-6e958b449530.png)
![image](https://user-images.githubusercontent.com/39305007/234757968-cb0f11a5-c156-498f-b9b2-4ce539278ff6.png)
layout页中的布局添加el-scrollbar后,点分页的时候回滚的时候一直是0

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
