### ISSUE TITLE
在permission.js中，将useUserStore()赋予一个变量调用后报错，直接使用则没问题，为什么会这样？

### ISSUE THREAD

**Issue by luffywz** [yangzongzhuan/RuoYi-Vue3#163]
在permission.js中，如果我增加一行代码
`cosnt  userStore = useUserStore()`，后续代码中将useUserStore()替换为userStore，会有错误提示‘getActivePinia was called with no active Pinia. Did you forget to install pinia?’，直接用‘useUserStore()’则不会报错，为什么会这样呢？

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
