### ISSUE TITLE
动态路由刷新404

### ISSUE THREAD

**Issue by BINGW2019** [yangzongzhuan/RuoYi-Vue3#165]
vue3 + elementplus 动态路由刷新404

**Comment by Emmpty** [comment]
出现了同名路由  现在这个vue3版本是不在维护了的吗  这个问题都好久了

**Comment by stan900814** [comment]
> vue3 + elementplus 动态路由刷新404

https://github.com/yangzongzhuan/RuoYi-Vue3/issues/165#issue-1699118144

**Comment by xilPikachu** [comment]
你解决了吗？我是401

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
