### ISSUE TITLE
分页组件样式问题

### ISSUE THREAD

**Issue by Rainyun** [yangzongzhuan/RuoYi-Vue3#166]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/49849992/3f395613-c6ac-4b23-b770-974ca449284b)
分页组件会在最右侧，样式没有跟表格对齐！

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
