### ISSUE TITLE
为什么login登录的验证码不显示 

### ISSUE THREAD

**Issue by webDev-zc** [yangzongzhuan/RuoYi-Vue3#167]
我是直接拉下来 安装好依赖 yarn dev 直接跑的
![Snipaste_2023-05-18_11-18-00](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/115536351/0e25c670-529f-468b-a779-71d4b1a65ffc)
![Snipaste_2023-05-18_11-18-12](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/115536351/ee97b61a-4d76-4fa8-8fc9-1db0a2c40ad1)

**Comment by gzzywoo** [comment]
后端没运行起来，或者没有配置连通后端

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
