### ISSUE TITLE
vscode components下面的文件vscode debug不准

### ISSUE THREAD

**Issue by yangganboy** [yangzongzhuan/RuoYi-Vue3#168]
vscode components下面的文件vscode debug不准,行号是对的，但是文件不对。
请问有什么解决办法吗？貌似是auto-import导致的。
不过不是很影响使用，chrome里面debug也差不多

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
