### ISSUE TITLE
ImgaePreview组件在表格中打开预览与表格样式冲突问题

### ISSUE THREAD

**Issue by zhaohuaishuai** [yangzongzhuan/RuoYi-Vue3#170]
应该将 append-to-body 改为  preview-teleported 否则会出来表格与预览区域的z-index层叠样式混乱问题

`
<el-image
      :src="`${realSrc}`"
      fit="cover"
      :style="`width:${realWidth};height:${realHeight};`"
      :preview-src-list="realSrcList"

      preview-teleported
    >
      <template #error>
        <div class="image-slot">
          <el-icon><picture-filled /></el-icon>
        </div>
      </template>
    </el-image>
`

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
