### ISSUE TITLE
editor 富文本编辑器  添加图片 给的是base64串  如果图片过多会导致保存/修改失败  

### ISSUE THREAD

**Issue by Gpicachu** [yangzongzhuan/RuoYi-Vue3#172]
editor 富文本编辑器 添加图片 给的是base64串 如果图片过多会导致保存/修改失败

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
