### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by AdminQQZ** [yangzongzhuan/RuoYi-Vue3#173]
菜单栏修改名称不行、

**Comment by AdminQQZ** [comment]
广告一直挂着，就是不修复，时不时就发几个更新文字文件

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
