### ISSUE TITLE
点击菜单栏时 route-view 时而显示，时而不显示

### ISSUE THREAD

**Issue by zw-store** [yangzongzhuan/RuoYi-Vue3#175]
我点击菜单栏的时候 vue-devtool 观察到了组件渲染内容，也有组件内部的变量显示，二级路由时而显示，时而不显示，首页Index也是如此，这是什么问题，我将路由history 换成webHash 也是不需，component 的组件key换成了唯一的name 也是不行

```javascript
<RouterView>
      <template #default="{ Component, route }">
        <transition name="fade-transform" mode="out-in">
          <KeepAlive :include="tagsViewStore.cachedViews">
            <component v-if="!route.meta.link" :is="Component" :key="route.name" />
          </KeepAlive>
        </transition>
      </template>
    </RouterView>
```

**Comment by zw-store** [comment]
@yangzongzhuan 
![watermark](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/53395110/c6d73332-faeb-4070-a0e4-d81a9e4e8d12)
内容如此

**Comment by qiangzhang12** [comment]
你好这个问题解决了吗？

**Comment by qiangzhang12** [comment]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/139617473/63b648e3-c23b-42b3-8407-848a5c0893d9)

**Comment by qiangzhang12** [comment]
key出问题了

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
