### ISSUE TITLE
dict-tag组件bug

### ISSUE THREAD

**Issue by dongshuke** [yangzongzhuan/RuoYi-Vue3#181]
在使用多选字典时, 数据为: `1,2,3`
 在列表显示时, 最后都会多出一个 ` 0`
 `<template v-if="unmatch && showValue"> {{ unmatchArray | handleArray }} </template>`
应该是这段代码的问题, 不知道应该怎么修改
望大佬指点

**Comment by guzijian123** [comment]
同样的一个问题  我是后面删除了这段 模板代码后就没有了，没有发现删除后有什么问题，

**Comment by dongshuke** [comment]
> 同样的一个问题 我是后面删除了这段 模板代码后就没有了，没有发现删除后有什么问题，

这段代码应该是用来显示, 无匹配数据的原value的, 现在这段代码就没用上, 删除应该也没什么影响

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
