### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by MrXiaoZheng** [yangzongzhuan/RuoYi-Vue3#182]
在系统管理的菜单管理中添加新的菜单级之后，在第一次点击新的菜单的时候页面能够成功刷新，展示页面内容 ，在第二次点击其他页面的时候页面地址跳转成功但是页面无法刷新出来，必须手动刷新一下才能显示页面内容

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
