### ISSUE TITLE
表单构建页面无法正常打开

### ISSUE THREAD

**Issue by jxlgzwh** [yangzongzhuan/RuoYi-Vue3#183]
一、碰到的问题
表单构建页面无法正常打开，如图所示
![7fe6bdef11c4ba110712824e6f75d5f](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/7359454/e17a61ec-493c-4ded-8c0c-368e97bf95a9)

二、问题描述

2.1 浏览器 f12 发现无报错

2.2 控制台启动没有发现报错

![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/7359454/0b0ae5a3-0f6b-4ec7-9489-61dbbc01a8bc)

**Comment by plingply** [comment]
表单构建功能都没有，空页面

**Comment by yangzongzhuan** [comment]
Vue3版本暂时还没有实现这个功能。
