### ISSUE TITLE
急急急！打包后then方法不执行，开发环境一切正常

### ISSUE THREAD

**Issue by z4117758** [yangzongzhuan/RuoYi-Vue3#184]
generateRoutes(roles) {
      return new Promise((resolve, reject) => {
        this.sidebarRouters = [];
        // 向后端请求路由数据
        const res = { data: tempMenu };
        // getRouters().then(res => {
        const sdata = JSON.parse(JSON.stringify(res.data));
        const rdata = JSON.parse(JSON.stringify(res.data));
        const defaultData = JSON.parse(JSON.stringify(res.data));
        const sidebarRoutes = filterAsyncRouter(sdata); // 侧边栏路由
        const rewriteRoutes = filterAsyncRouter(rdata, false, true); // 顶部菜单路由
        const defaultRoutes = filterAsyncRouter(defaultData); // 默认路由
        const asyncRoutes = filterDynamicRoutes(dynamicRoutes);
        asyncRoutes.forEach((route) => {
          router.addRoute(route);
        });
        this.setRoutes(rewriteRoutes);
        this.setSidebarRouters(constantRoutes.concat(sidebarRoutes));
        this.setDefaultRoutes(sidebarRoutes);
        this.setTopbarRoutes(defaultRoutes);
        // console.log(sidebarRoutes);
        resolve(sidebarRoutes);
        // })
      }).catch(() => {
        reject("失败");
      });
    },
这个方法 里能执行到   resolve(sidebarRoutes); 这一步 。但在调用这个函数的时候.then里的方法执行不了。<开发环境一切正常,打包后就会出现then里不执行的问题>

**Comment by z4117758** [comment]
发现卡住的原因在：给左侧菜单重新复制渲染，然后卡死。目前没有解放方案。左侧带单不用computed 直接渲染也会卡死

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
