### ISSUE TITLE
进入页面表单时富文本框TypeError: Cannot read properties of null (reading 'slice')

### ISSUE THREAD

**Issue by 1759176121** [yangzongzhuan/RuoYi-Vue3#185]
1.错误提示
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'slice')
    at maybeClone (vue-quill.esm-bundler.js:208:54)
    at setContents (vue-quill.esm-bundler.js:297:29)
    at initialize (vue-quill.esm-bundler.js:146:13)
    at vue-quill.esm-bundler.js:118:13
2.问题场景
a.进入页面先点击修改按钮，富文本框赋值正常，再点击新增按钮，富文本框数据没有被清空，还是上次修改时的数据
b.刷新页面，先点击新增按钮，控制台报上述错误提示，同时当前页面按钮点击全部失效报上述错误

**Comment by L-2945841899** [comment]
问题解决了嘛？我也遇到了这个问题

**Comment by 1759176121** [comment]
我的解决方案是：找到添加按钮，重新给富文本框赋空字符串，data.form.content = "";
/** 新增按钮操作 */
function handleAdd() {
  reset();
  data.form.content = "";
  open.value = true;
  title.value = "添加商品信息";
}

**Comment by minliuhua** [comment]
editor富文本组件，判空导致的，正确判空就可以了

![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/65475189/44fab9db-9500-4752-b2d7-6a07ac05973b)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
