### ISSUE TITLE
vue3版本在功能上和vue2保持一致吗？是否有功能上的缺陷，比如流程方面

### ISSUE THREAD

**Issue by pei-han** [yangzongzhuan/RuoYi-Vue3#186]
vue3版本的在功能上和vue2保持一致吗？是否有功能上的缺陷，比如流程方面。
在做基础架构的选型，懂vue3，如果vue3版本相对vue2在功能上有缺陷的话，可以选择vue2。
功能完整的情况下，倾向选择更新的vue3，麻烦支个招，谢谢

**Comment by pei-han** [comment]
@yangzongzhuan  感谢回答

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
