### ISSUE TITLE
yarn 安装依赖报错,npm没问题

### ISSUE THREAD

**Issue by tiezhu001** [yangzongzhuan/RuoYi-Vue3#189]
yarn 报错如下
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/46275305/4af15b79-556b-4dec-8e5e-0536202fccf5)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
