### ISSUE TITLE
前端发送请求到后端传参问题

### ISSUE THREAD

**Issue by 923943148** [yangzongzhuan/RuoYi-Vue3#19]
如果axios发请求，不使用封装好的这个import request from '@/utils/request'，应该怎么传参，才能后端权限验证通过。
如果直接拼headers: { Authorization: "Bearer " + getToken() } 不生效！，求救！

**Comment by zhuhaobam** [comment]
config.headers['Authorization'] = 'Bearer ' + getToken() // 让每个请求携带自定义token 请根据实际情况自行修改

**Comment by zhuhaobam** [comment]
![image](https://user-images.githubusercontent.com/15319171/154184849-6a820a4f-2642-4e88-aa9f-3b2ea75dbc24.png)

**Comment by zhuhaobam** [comment]
headers此处代表的就是请求头，中括号属于对象操作属性的两种方式之一，你想往请求头在这里改或者增加内容。

**Comment by zhuhaobam** [comment]
你直接去src/utils/request.js改就好了，至于这个token你看src/store/modules/user.js,里面
![image](https://user-images.githubusercontent.com/15319171/154186230-1d830c15-41ed-40da-b1a8-cfdaa5b13364.png)
