### ISSUE TITLE
配置数据表，设置上级菜单的时候，回显只显示菜单ID

### ISSUE THREAD

**Issue by Niushuaik** [yangzongzhuan/RuoYi-Vue3#191]
在TreeSelect组件里面监听一下props.options变化，父组件请求数据在子组件渲染之后，不然回显为菜单ID
`watch(()=>props.options, () => {
    initHandle();
})`

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
