### ISSUE TITLE
RuoYi-Vue3工程对应的前端系统有demo地址吗？类似http://vue.ruoyi.vip/system/role一样的

### ISSUE THREAD

**Issue by gpf1053149467** [yangzongzhuan/RuoYi-Vue3#195]
我发现有些不一样，http://vue.ruoyi.vip/system/role这个系统的角色管理中的操作是：（文字）修改、删除、更多（展开后是 数据权限、分配用户）；但是RuoYi-Vue3代码中的却是以图标的形式平铺开的4个。
虽然这很好改，但是这个细微的差异点让我觉得会不会还有其他地方，是此工程和demo演示地址不一样的？
或者说是我找错了demo地址吗？
求解答~感谢!

**Comment by wj2y** [comment]
若依官网有哈

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
