### ISSUE TITLE
keep-alive失效的问题

### ISSUE THREAD

**Issue by stan900814** [yangzongzhuan/RuoYi-Vue3#198]
点击tag切换路由时，缓存失效，并且onActivated, onDeactivated生命周期均没有执行。检查菜单配置也没有问题。请问有遇到相同情况的吗

**Comment by lovesL** [comment]
我也有这种情况

**Comment by yingyue520** [comment]
我也又这种情况

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
