### ISSUE TITLE
目录名src/layout/components/TagsView/的TagsView与代码中的大小写一致，抛错；手工改成一致后，也运行出错。

### ISSUE THREAD

**Issue by lawbiao** [yangzongzhuan/RuoYi-Vue3#2]
> vite

 > src/layout/components/index.js:4:36: error: Could not resolve "./TagsView/index.vue"
    4 │ export { default as TagsView } from './TagsView/index.vue'
      ╵                                     ~~~~~~~~~~~~~~~~~~~~~~

**Comment by yangzongzhuan** [comment]
试了下没有你说的问题。自己检查下node版本是否>12。另外问题请在[RuoYi-issues](https://gitee.com/y_project/RuoYi-Vue/issues)里提问，方便统一处理。
你也可以试试如下流程。
```bash
# 克隆项目
git clone https://github.com/yangzongzhuan/RuoYi-Vue3.git

# 进入项目目录
cd RuoYi-Vue3

# 安装依赖
yarn --registry=https://registry.npm.taobao.org

# 启动服务
yarn dev
```

**Comment by yangzongzhuan** [comment]
好像是Linux系统里面会区分大小写，我刚重新改了一下目录，你可以再试试看~
