### ISSUE TITLE
to.title && useSettingsStore().setTitle(to.meta.title)

### ISSUE THREAD

**Issue by qdnqwlgithub** [yangzongzhuan/RuoYi-Vue3#202]
这行代码是什么意思？出自permission.js

`
  if (getToken()) {
    to.title && useSettingsStore().setTitle(to.meta.title)

`

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
