### ISSUE TITLE
新增菜单选择 icon 完毕，点击其它输入框会触发选择 icon

### ISSUE THREAD

**Issue by BNTang** [yangzongzhuan/RuoYi-Vue3#203]
![a](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/78400939/f983cb7d-184c-4cce-892c-f2352c39fa4a)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
