### ISSUE TITLE
能否基于vue3版本提供一个国际化的配置文档

### ISSUE THREAD

**Issue by blue-tears** [yangzongzhuan/RuoYi-Vue3#205]
能否基于vue3版本提供一个国际化的配置文档

**Comment by yangbuyiya** [comment]
饿了么文档写的明明白白 配置一下就ok了

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
