### ISSUE TITLE
添加公告 的富文本样式问题；

### ISSUE THREAD

**Issue by yhx-yhx** [yangzongzhuan/RuoYi-Vue3#209]
.editor, .ql-toolbar {
  max-width: 100%;
  /* width: 100%; */
  white-space: pre-wrap !important;
  line-height: normal !important;
}

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
