### ISSUE TITLE
修改生成代码的配置信息时，报错

### ISSUE THREAD

**Issue by WuzhongPeople** [yangzongzhuan/RuoYi-Vue3#21]
系统工具-》代码生成-》数据列表的编辑图表按钮-》点击提交按钮报错
JSON parse error: Unrecognized field "required" (class com.ruoyi.generator.domain.GenTableColumn), not marked as ignorable; nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "required" (class com.ruoyi.generator.domain.GenTableColumn), not marked as ignorable (24 known properties: "updateBy", "columnName", "queryType", "isInsert", "isPk", "params", "isList", "searchValue", "columnType", "columnId", "createBy", "isEdit", "updateTime", "javaField", "javaType", "isQuery", "isIncrement", "createTime", "dictType", "sort", "tableId", "columnComment", "isRequired", "htmlType"]) at [Source: (PushbackInputStream); line: 1, column: 985] (through reference chain: com.ruoyi.generator.domain.GenTable["columns"]->java.util.ArrayList[0]->com.ruoyi.generator.domain.GenTableColumn["required"])

**Comment by yangzongzhuan** [comment]
请提供出能复现问题的详细步骤和相关表结构。
