### ISSUE TITLE
富文本编辑器添加了图片可以缩放的代码部署到nginx报错

### ISSUE THREAD

**Issue by mlvi** [yangzongzhuan/RuoYi-Vue3#210]
若依的富文本编辑器添加了图片可以缩放的代码 本地跑没问题 打包部署到nginx就报错是咋回事
TypeError: Super expression must either be null or a function, not undefined

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
