### ISSUE TITLE
Cannot read properties of null (reading 'slice') 

### ISSUE THREAD

**Issue by minliuhua** [yangzongzhuan/RuoYi-Vue3#214]
editor富文本组件，判空导致的，正确判空就可以了

![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/65475189/3a5983e2-0bba-477d-b9a8-f46e61e5a249)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
