### ISSUE TITLE
请问我用webstorm为什么import文件的时候显示‘未安装模块’，但实际可以正常运行

### ISSUE THREAD

**Issue by Furious1106** [yangzongzhuan/RuoYi-Vue3#217]
<img width="771" alt="Snipaste_2023-09-08_10-32-48" src="https://github.com/yangzongzhuan/RuoYi-Vue3/assets/53113723/0e27b550-638d-49c9-9202-bdaea4b92276">

项目中所有的import都显示‘未安装模块’，虽然项目可以正常运行，但所有的方法都没法按住ctrl直接点进去，开发起来很不方便

**Comment by lszgf1234** [comment]
```
# 根目录添加文件`jsconfig.json`
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "exclude": ["node_modules", "dist"]
}

# or 更新webstorm到最新版

```
