### ISSUE TITLE
Vue3版本后台管理  一键生成代码  现在生成的时还是vue2的代码格式  怎么生成vue3的代码风格

### ISSUE THREAD

**Issue by MengYaoSai** [yangzongzhuan/RuoYi-Vue3#219]
Vue3版本后台管理  一键生成代码  现在生成的时还是vue2的代码格式  怎么生成vue3的代码风格

**Comment by chrvip** [comment]
后端模板目录vm里的 vue 有一个 v3，看一下里面的 readme.txt

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
