### ISSUE TITLE
有时新增菜单访问404

### ISSUE THREAD

**Issue by Nockla** [yangzongzhuan/RuoYi-Vue3#221]
使用菜单管理新增了几个菜单，有的能够正常显示，但是有的就是404
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/74718856/c0c677ea-9d23-43c9-8dbb-bb6fbc84265d)
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/74718856/b7afe007-d572-402e-8922-2f56e8ec83a2)
其他的菜单都一切正常，只有这个会出错，而当我修改路由地址后，就又正常了
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/74718856/d3202e71-c197-48f2-be7e-a936848c1337)
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/74718856/bcd96210-8e74-4b47-bae2-87992b95872b)
没搞明白什么原因

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
