### ISSUE TITLE
tailwind css不起作用

### ISSUE THREAD

**Issue by LxsZxh** [yangzongzhuan/RuoYi-Vue3#223]
去掉vite.config.js的如下代码可以生效，但会影响样式，有好一点的解决办法吗？
css: {
      postcss: {
        plugins: [
          {
            postcssPlugin: 'internal:charset-removal',
            AtRule: {
              charset: (atRule) => {
                if (atRule.name === 'charset') {
                  atRule.remove()
                }
              },
            },
          },
        ],
      },
    },

**Comment by sendking** [comment]
unocss

**Comment by LxsZxh** [comment]
> unocss

unocss不会受上面的规则影响吗

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。

**Comment by whidy** [comment]
@LxsZxh 
我看了下，根据TailwindCSS的文档：[Install Tailwind CSS with Vite](https://tailwindcss.com/docs/guides/vite#vue)

他会创建一个`postcss.config.js`文件

而vite配置中，也就是你发的这个配置覆盖了他，导致了问题。故而，我们可以这样做：

首先删除你上面发的配置，然后修改`postcss.config.js`，讲若依自带的内置插件追加进去，比如改成这样：

```
export default {
  plugins: [
    {
      //fix:error:stdin>:7356:1: warning: "@charset" must be the first rule in the file
      postcssPlugin: "internal:charset-removal",
      AtRule: {
        charset: (atRule) => {
          if (atRule.name === "charset") {
            atRule.remove();
          }
        },
      },
    },
    require("tailwindcss"),
    require("autoprefixer"),
  ],
};
```

我自己测试是没有问题的，更多学习可以参考：

* [PostCSS AtRule](https://postcss.org/api/#atrule)
* [PostCSS的配置文件](https://github.com/postcss/postcss?tab=readme-ov-file#css-in-js)

当然根本原因我推测是因为`vite.config.js`配置postcss这段覆盖了`postcss.config.js`所致。

**Comment by LxsZxh** [comment]
感谢回复，我现在去试一下






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangzongzhuan/RuoYi-Vue3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月29日(星期五) 中午1:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangzongzhuan/RuoYi-Vue3] tailwind css不起作用 (Issue #223)





 
@LxsZxh
 我看了下，根据TailwindCSS的文档：Install Tailwind CSS with Vite
 
他会创建一个postcss.config.js文件
 
而vite配置中，也就是你发的这个配置覆盖了他，导致了问题。故而，我们可以这样做：
 
首先删除你上面发的配置，然后修改postcss.config.js，讲若依自带的内置插件追加进去，比如改成这样：
 export default {   plugins: [     {       //fix:error:stdin&gt;:7356:1: warning: ***@***.***" must be the first rule in the file       postcssPlugin: "internal:charset-removal",       AtRule: {         charset: (atRule) =&gt; {           if (atRule.name === "charset") {             atRule.remove();           }         },       },     },     require("tailwindcss"),     require("autoprefixer"),   ], };  
我自己测试是没有问题的，更多学习可以参考：
  
PostCSS AtRule
 
PostCSS的配置文件
  
当然根本原因我推测是因为vite.config.js配置postcss这段覆盖了postcss.config.js所致。
