### ISSUE TITLE
刷新后401，认证失败无法访问系统资源

### ISSUE THREAD

**Issue by xilPikachu** [yangzongzhuan/RuoYi-Vue3#224]
单独前端版本，跨域调用官方接口
模块中（如/system/user页面）刷新页面时，
页面出现认证失败，无法访问系统资源，code401，
且再次刷新没有任何反应
查看接口调用，调用的是/system/user接口（不存在），实际应当调用/getInfo和/getRouters接口
刷新时也未进入router.beforeEach方法

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
