### ISSUE TITLE
eslint + prettier 安装问题

### ISSUE THREAD

**Issue by KingPengZero** [yangzongzhuan/RuoYi-Vue3#225]
有个问题，这个vue3的项目，按照eslint官方的方法，还有搭配prettier，项目能跑起来，但是vscode报红特别多

### Lint with

- [ESLint](https://eslint.org/)
- [eslint-plugin-vue](https://eslint.vuejs.org/user-guide/)
- [prettier](https://prettier.io/docs/en/install)

```sh
报红太多，暂时remove eslint
yarn lint
```

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
