### ISSUE TITLE
vue3版本的ruoyi是不是有内存占用不释放的问题，导致浏览器卡顿

### ISSUE THREAD

**Issue by yunkuotianxian** [yangzongzhuan/RuoYi-Vue3#226]
1 原生的ruoyi基于vue3项目
2 启动后点击“系统管理”
3 一次点击“系统管理“下菜单50次，记录内存占用情况
4 再点击“系统管理”下菜单50次，再记录内存占用会一直增加
5 如果这样用手点就可以把浏览器点死
6 vue2的版本的不存在这个问题，点击到一定次数，内存占用是恒定的
7 vue3的AppMain.vue是<router-view v-if="!$route.meta.link" :key="key" />   通过key的切换把上一次的组件销毁（如果不在缓存里），但是vue3的实现是不一样的，通过<component :is="Component" :key="route.path"/>来实现，切换后只要不在缓存里的也不销毁，继续占用？是这样吗？
8 这个vue3项目的占用内存如何解决，谢谢大家帮助

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
