### ISSUE TITLE
代码生成模块，前端无代码

### ISSUE THREAD

**Issue by jaimorlin** [yangzongzhuan/RuoYi-Vue3#229]
view/tool/build下没有相关的生成代码的东西。导致导航，表单构建，无功能。
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/41357283/991ca860-d074-4ca3-971c-745981a2c70c)

**Comment by yangzongzhuan** [comment]
这个功能在vue3版本中还未实现。
