### ISSUE TITLE
定时任务 的 cron表达式 年的周期处理应该是有问题

### ISSUE THREAD

**Issue by vastwu1** [yangzongzhuan/RuoYi-Vue3#231]
else if (value.indexOf("/") > -1) {
        const indexArr = value.split('#')
        average01.value = Number(indexArr[1])
        average02.value = Number(indexArr[0])
        radioValue.value = 4
    }

应该是

else if (value.indexOf("/") > -1) {
        const indexArr = value.split('/')
        average01.value = Number(indexArr[0])
        average02.value = Number(indexArr[1])
        radioValue.value = 4
    }

**Comment by yangzongzhuan** [comment]
嗯，改了
