### ISSUE TITLE
作者你好，有没有TS版本？

### ISSUE THREAD

**Issue by lihanqiang** [yangzongzhuan/RuoYi-Vue3#233]
有没有TS版本？

**Comment by houliangyu** [comment]
没看到 应该是没有 去官网看看吧 https://ruoyi.vip/

**Comment by houliangyu** [comment]
https://github.com/zzh948498/RuoYi-Vue3-ts  这里好像有人发了一版本ts的不知道如何

**Comment by lihanqiang** [comment]
这版还不如原版呢。。。改个后缀就完事了😭发自我的 iPhone在 2024年1月13日，10:54，填不满的海 ***@***.***> 写道：﻿
https://github.com/zzh948498/RuoYi-Vue3-ts  这里好像有人发了一版本ts的不知道如何

**Comment by yangzongzhuan** [comment]
目前还没有 可以去项目扩展里面找找
http://doc.ruoyi.vip/ruoyi-vue/document/xmkz.html
