### ISSUE TITLE
图片上传组件（ImageUpload）预览和删除按钮显示问题

### ISSUE THREAD

**Issue by zhouzhigang-GitHub** [yangzongzhuan/RuoYi-Vue3#237]
.el-upload-list--picture-card .el-upload-list__item-actions span+span {
    margin-left: 1rem;
}
原来的样式，margin-left为：1rem，左外边距过大，导致无法看到预览和删除按钮
![1706859612582](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/74940606/e80f814d-cf3c-46f6-8c67-421e3be72c7a)

修改方案：在ImageUpload组件中添加即可
:deep(.el-upload-list--picture-card .el-upload-list__item-actions span+span) {
    margin-left: 45px;
}
![1706859612585](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/74940606/d80866dd-35db-4d4a-a45f-ea9e7606e8e6)

**Comment by yangzongzhuan** [comment]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/19240310/cffbbc01-8fae-4f98-b538-4cc33250dc10)
测试验证了一下，按钮挺正常的，没有问题。

**Comment by mylizhixiang** [comment]
谢谢！
