### ISSUE TITLE
富文本编辑器上传图片问题

### ISSUE THREAD

**Issue by 532836459** [yangzongzhuan/RuoYi-Vue3#238]
通过富文本编辑器上传的图片会把/dev-api路径给保存到数据库中，实际上应该是以/profile开头的才对吧
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/48585764/e579d904-0172-4454-abfc-1bc4a2dc9715)

**Comment by yangzongzhuan** [comment]
都可以，如果是/profile，还要单独配置代理 /dev-api或/prod-api不需要配置，默认有代理。可以自己根据实际情况调整
