### ISSUE TITLE
vue3为什么不是用TypeScript呢

### ISSUE THREAD

**Issue by XuXiaoXu11** [yangzongzhuan/RuoYi-Vue3#240]

**Comment by github-cherry** [comment]
那你试试[Geeker-Admin](https://gitee.com/HalseySpicy/Geeker-Admin)

![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/43592730/7a5db7ab-2aa5-426e-bafa-5dfa61311fb7)

**Comment by yangzongzhuan** [comment]
js template 使用起来更简单更容易理解。
