### ISSUE TITLE
bin目录干啥的？能删吗？

### ISSUE THREAD

**Issue by chergn** [yangzongzhuan/RuoYi-Vue3#242]
删了会影响什么吗？
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/43592730/e19300b7-d327-4d9b-89d7-a0b9cdb064fa)

**Comment by wzs28150** [comment]
看里面的文件就应该知道啊 。。。都是win下运行项目打包项目的快捷批处理文件，点了里面的.bat可以直接运行项目或打包项目，用不上可以删掉，不影响项目
