### ISSUE TITLE
页签刷新就出错

### ISSUE THREAD

**Issue by chergn** [yangzongzhuan/RuoYi-Vue3#243]
比如已经打开三五个页签，刷新后就剩两个：当前页和首页
![动画](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/43592730/90f3e4a5-548f-462c-9d6f-c8331928c61d)

**Comment by Aesthetlc** [comment]
就是这么设计的

**Comment by arm-liang** [comment]
自己缓存一个 modules/tagsView.js `visitedViews` 变量就好了

**Comment by yangzongzhuan** [comment]
设计如此
