### ISSUE TITLE
希望能项目自带unocss

### ISSUE THREAD

**Issue by chergn** [yangzongzhuan/RuoYi-Vue3#244]
可以像[vue-naive-admin](https://gitee.com/isme-admin/vue-naive-admin#%E7%89%B9%E6%80%A7)一样项目配置上unocss吗？
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/43592730/0cbd566f-6559-464c-979c-67e8fcb3ceab)
这种预设的css没有量子化样式引擎更优雅，根据引用的class动态生成css

**Comment by yangzongzhuan** [comment]
可以自己加入进去
