### ISSUE TITLE
    RuoYi-Vue3/src/utils  /request.js 里的这个语句应该如何理解啊

### ISSUE THREAD

**Issue by cscsb** [yangzongzhuan/RuoYi-Vue3#245]
const isToken = (config.headers || {}).isToken === false

我是菜鸟，看不懂这个

**Comment by chenxi2008** [comment]
()

> const isToken = (config.headers || {}).isToken === false
> 
> 我是菜鸟，看不懂这个

判断 （config.headers.isToken === false）
(config.headers || {}) 表示如果对象中没有headers属性时取一个空对象，不然相当于[undefined.isToken] 就报错了

**Comment by elarbor** [comment]
自定义的参数，放在`headers`里的。接口调用处可以传`isToken`，不传或传false就是这个接口不校验token。比如[获取验证码](https://github.com/yangzongzhuan/RuoYi-Vue3/blob/master/src/api/login.js#L55)的接口
