### ISSUE TITLE
环境配置缺失提示

### ISSUE THREAD

**Issue by wkclz** [yangzongzhuan/RuoYi-Vue3#25]
问题：
.env 配置文件在意外导致配置缺失时，（VITE_BUILD_COMPRESS 配置只在生产打包才需要，而且是必需的，本地 dev 不需要也不会报错）提示为代码报错，未有具体报错提示。
两个可行的建议：
1. 配置缺失时，赋值默认配置
2. 配置缺失时，报告缺失项目（实际上报空了，但位置与此配置无关，导致问题排查难度大增）

**Comment by yangzongzhuan** [comment]
你PR上来吧。
