### ISSUE TITLE
axios响应拦截器优化建议

### ISSUE THREAD

**Issue by yuezhishun** [yangzongzhuan/RuoYi-Vue3#250]
[这里判断接口应答内容中的code字段](https://github.com/yangzongzhuan/RuoYi-Vue3/blob/6a10846b6d364219bfa3cff561a47753d3546ea8/src/utils/request.js#L77)
在axios的响应拦截器中，判断body中的code会出现接口兼容的问题，建议判断http应答的状态码，理由：工具类尽量避免业务处理，不管http状态码还是body中的状态码，都交给业务代码处理
```
    // 未设置状态码则默认成功状态
    const code = res.status || 200;
```
比如图验接口应答里有就会报错
```
{"code":"1234","uuid":"xxxxxx","img":"xxxxxxxx"}
```

**Comment by yx1314** [comment]
我觉得这个你可以写成数组。只要是数组内的code值就都是正常返回值。但是对于项而言。后端的code不统一。很奇怪

**Comment by yangzongzhuan** [comment]
code必须统一 不能随便定义
