### ISSUE TITLE
登录页验证码出不来，报错500，怎么解决？

### ISSUE THREAD

**Issue by zrting** [yangzongzhuan/RuoYi-Vue3#254]
拉取项目安装依赖，启动项目登录页面验证码出不来，提示系统接口500异常，控制台：[vite] http proxy error at /captchaImage:Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] **(node:net:1278:16) 
然后将vite.config.js中proxy中：target:** 'http://localhost:80' 端口号改为80，验证码接口304，还是加载不出来，请问这个问题怎么解决呢？望大佬能看到

**Comment by nidegexing** [comment]
同样的问题，朋友们有遇到么，什么原因呀，怎么解决

**Comment by scallopsF** [comment]
我也是同样的问题 ，改成自己的服务接口了，在vue2的项目上可以，在这个vue3的项目上就报错 304

**Comment by yangzongzhuan** [comment]
前端是80，后端是8080，不要随便去修改，你这种情况是没有启动后端，配套后端下载地址
 
多模块下载地址：https://gitee.com/y_project/RuoYi-Vue

 单应用下载地址：https://github.com/yangzongzhuan/RuoYi-Vue-fast
