### ISSUE TITLE
登录页面无法显示验证码

### ISSUE THREAD

**Issue by cscsb** [yangzongzhuan/RuoYi-Vue3#257]
![2024-04-06_084339](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/49179157/7657b063-a5a5-4283-b45e-021dfe5c999d)

并且显示接口500错误

**Comment by lichenglong-blog** [comment]
我也是呀，咋登录不上呀

**Comment by yangzongzhuan** [comment]
启动后端，配套后端下载地址

多模块下载地址：https://gitee.com/y_project/RuoYi-Vue

单应用下载地址：https://github.com/yangzongzhuan/RuoYi-Vue-fast
