### ISSUE TITLE
hash下 index页面跳转优化

### ISSUE THREAD

**Issue by wkclz** [yangzongzhuan/RuoYi-Vue3#26]
场景：
hash 模式 oss 部署（没法 try_file） 的情况下，初始页面跳转 /index 会尝试去找 /index 而导致404

解决方案建议：
考虑到 hash 场景还没办法设置 try_file ，在跳转 /index 的地方，变更为跳转  / 即可
包含（暂时发现的）：
1. NavBar 退出的跳转，
2. 404 页面跳转到首页
3. request.js 中 store.dispatch('LogOut') 下的跳转
为保证修复完整，还是提问题给大佬修复为妙

**Comment by yangzongzhuan** [comment]
参考文档 http://doc.ruoyi.vip/ruoyi-vue/document/qdsc.html#应用路径
