### ISSUE TITLE
接口异常500呀，验证码刷不出来

### ISSUE THREAD

**Issue by lixiang-8023** [yangzongzhuan/RuoYi-Vue3#263]
![Uploading WX20240428-115110.png…]()

**Comment by pistachio0812** [comment]
这个问题是服务器有问题，ping192.168.2.80ping不通

**Comment by yangzongzhuan** [comment]
启动后端，配套后端下载地址

多模块下载地址：https://gitee.com/y_project/RuoYi-Vue

单应用下载地址：https://github.com/yangzongzhuan/RuoYi-Vue-fast
