### ISSUE TITLE
path重复时404的bug

### ISSUE THREAD

**Issue by jinceon** [yangzongzhuan/RuoYi-Vue3#264]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/1641265/e4e9b554-0f42-4877-9022-ea4b887a04f8)

代码改动很简单，我就不提pr了，有需要的小伙伴们自取

![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/1641265/43965e85-5be3-430f-8998-5f9a02f08123)

**Comment by arm-liang** [comment]
这个是新版vue-router特性，存在同名name的route，后面的route会覆盖前面的route
js版本，store/modules/permission.js
````javascript
// action
generateRoutes(roles) {
// ...
  getRouters().then(()=>{
  // ...
    routeNameMap.clear()
  })
}
````
````javascript
/**@type {Map<string,number>} */
const routeNameMap = new Map()
function filterAsyncRouter(.........){
   return asyncRouterMap.filter(route => {

    if (route.component) {
      if(type && route.name){
        // name 不重复，vue-router 相同name的route会覆盖
        const nameCount = routeNameMap.get(route.name)
        if(nameCount){
          route.name = route.name + (nameCount + 1)
          routeNameMap.set(route.name, nameCount+1)
        }
        routeNameMap.set(route.name, 1)
      }
      // ......
  })

}
````

**Comment by yangzongzhuan** [comment]
由于`Vue3 Router`存在名称相同的Name，会先删除路由，再添加路由，所有会导致前面的路由无法被访问。

问题反馈给`Router`官方也一直很久没有结果，所以大家可以先更新提交代码，出现重名冲突可以在菜单管理可以自定义Name，和对应页面组件的Name保持一致，防止缓存失效。

前端 [菜单管理新增路由名称](https://github.com/yangzongzhuan/RuoYi-Vue3/commit/c227751acb1162e5c303fc0efc15b544d9226362)
后端 [菜单管理新增路由名称](https://gitee.com/y_project/RuoYi-Vue/commit/a96d4bf2eda9dfde4a8efdb32cb619b95c80ab1e)

**Comment by jinceon** [comment]
我觉得router官方的设计没问题，确定不该重复。
但我觉得这个改动不好。
因为用户就不关注name，只要保证唯一即可。
那为什么不自动拼接父menu的path呢？

**Comment by elarbor** [comment]
确实啊，文件的name就该 `父path+本path`
![image](https://github.com/user-attachments/assets/a50e3c42-732d-4e80-8e7c-af867a0da56b)
