### ISSUE TITLE
页面切换不刷新

### ISSUE THREAD

**Issue by linghanwu-code** [yangzongzhuan/RuoYi-Vue3#265]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/65112674/71b2e6ec-a761-4b27-9dda-10f4e24d9320)

**Comment by Crown017** [comment]
路由写错了

**Comment by linghanwu-code** [comment]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/65112674/3c0bb97f-016b-433a-8cdb-17e2849c506a)
这样解决了

**Comment by bcd-github** [comment]
有详细的解决方法吗

**Comment by arm-liang** [comment]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/37470680/41bebc0c-e11c-4f4e-9ded-8d8393518d7d)
### 菜单默认开启了页面缓存
> 如果 页面name和路由配置的name相同，并且开启了缓存配置，页面才会走缓存

> ![image](https://private-user-images.githubusercontent.com/65112674/326739734-3c0bb97f-016b-433a-8cdb-17e2849c506a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODg1OTcsIm5iZiI6MTcxOTM4ODI5NywicGF0aCI6Ii82NTExMjY3NC8zMjY3Mzk3MzQtM2MwYmI5N2YtMDE2Yi00MzNhLThjZGItMTdlMjg0OWM1MDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3NTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MjM4M2VjZGQwZjViZTg0MjVhYWNlMzgyZjM4NGI3MTI3ZTUyMTZmYmVjYTgwNjM1YzczMDRlZmEwZDZmYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xGj2avfOCqxkRX1ARhSLMP3sjIR85K78W9ddFTcR3-I) 这样解决了

**Comment by yangzongzhuan** [comment]
注意缓存的事项：菜单管理开启缓存，路由名称和组件名称保持一致。
