### ISSUE TITLE
按钮在点击后除非点击页面，不然总是灰色的？

### ISSUE THREAD

**Issue by licf327** [yangzongzhuan/RuoYi-Vue3#269]
![灰色](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/53704156/ff39e800-47c2-4c69-9652-6ca8b5e6ef44)
这是为什么呢？

**Comment by arm-liang** [comment]
按钮 button focus 状态的默认效果

**Comment by yangzongzhuan** [comment]
按钮在点击后根据规范是不会失去焦点的，可以自己调整元素样式。
