### ISSUE TITLE
vue文件大小写问题

### ISSUE THREAD

**Issue by wkclz** [yangzongzhuan/RuoYi-Vue3#27]
问题：
git 本身大小写不敏感，在本地调戏代码，大小写修改后能正常，但到了线上编译总是提示找不到 vue 文件
修复建议：
1. 此问题应该是大家都喜欢范的错，可以完全避免不可能，创建 Wiki 的方式在里面说明（可以写明一个大小写规范）即可
2. 解决本项目内的大小写问题
    2.1 TagsView/index.vue
    2.2 Sidebar/index.vue
    2.3 layout/index.vue  （[router](https://github.com/yangzongzhuan/RuoYi-Vue3/tree/master/src/router)/index.js）找 index.vue 异常
其他的忘记了，但直接拉取 git 后编译就能看到问题。

**Comment by yangzongzhuan** [comment]
大小写的问题我记得很早就优化过。现在是没有了

**Comment by wkclz** [comment]
问题一直存在。git 对大小写不敏感。处理方式为，重命名目录，提交代码。再改回去，提交代码。才能被彻底替换掉
