### ISSUE TITLE
此版本的系统接口swagger带了8080端口号

### ISSUE THREAD

**Issue by yyhnwang** [yangzongzhuan/RuoYi-Vue3#272]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/45425333/5bad38aa-d03a-4855-9858-9991fd79577c)
访问时导致404

**Comment by yangzongzhuan** [comment]
访问8080没有问题，可以在后端配置，去掉pathMapping
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:
