### ISSUE TITLE
使用Arco Design Vue前端代替element ui 计划

### ISSUE THREAD

**Issue by munan718** [yangzongzhuan/RuoYi-Vue3#280]
有没有计划使用Arco Design Vue 前端

**Comment by Realybig** [comment]
Arco 相比目前的 el-plus 有什么有优点吗？

**Comment by yangzongzhuan** [comment]
没有计划，精力有限，环境自己集成后分享地址到项目扩展
http://doc.ruoyi.vip/ruoyi-vue/document/xmkz.html
