### ISSUE TITLE
小屏模式下菜单按钮点击无反应

### ISSUE THREAD

**Issue by 593496637** [yangzongzhuan/RuoYi-Vue3#286]
当屏幕缩小到左侧菜单隐藏后，点击显示菜单按钮无效果
<img width="924" alt="image" src="https://github.com/yangzongzhuan/RuoYi-Vue3/assets/15769004/f407c27c-41c0-4c17-a6e9-ff1f8736e78e">

**Comment by yangzongzhuan** [comment]
已修复，更新即可。 [修复移动端左侧菜单无法显示问题](https://github.com/yangzongzhuan/RuoYi-Vue3/commit/0780d9659b229f80a3c9788988ec7d9ccd63ddbb)
