### ISSUE TITLE
ElementPlusError: [ElOnlyChild] no valid child node found

### ISSUE THREAD

**Issue by z3214965** [yangzongzhuan/RuoYi-Vue3#29]
会有非常多的此类型警告，怎么处理？
![捕获](https://user-images.githubusercontent.com/18589356/155288346-bb30851b-4d00-445f-b41a-1db5dbb175ec.PNG)

**Comment by zhuhaobam** [comment]
你使用最新的代码吗，建议吧node_module删除掉，重新npm i   我的没有

**Comment by z3214965** [comment]
@zhuhaobam 
我使用的是最新，你没有这个问题？

**Comment by yangzongzhuan** [comment]
相同的问题 https://gitee.com/y_project/RuoYi-Vue/issues/I4Y0P3 有些版本没有，因为之前操作列没有用这种el-tooltip

**Comment by yangzongzhuan** [comment]
多谢提醒，已优化。
[优化控制台出现的ElOnlyChild错误](https://github.com/yangzongzhuan/RuoYi-Vue3/commit/32ee59f763692d9de237207aed9b976cde8a4815)
`https://github.com/yangzongzhuan/RuoYi-Vue3/commit/32ee59f763692d9de237207aed9b976cde8a4815`
