### ISSUE TITLE
cron生成的表达式hour优化

### ISSUE THREAD

**Issue by frp-server** [yangzongzhuan/RuoYi-Vue3#294]
现在所有的都按秒定时，RuoYi 3.8.8版本已经解决了这个bug，vue3版本看有空的话也改一下

**Comment by yangzongzhuan** [comment]
优化过了 [cron生成的表达式hour优化](https://github.com/yangzongzhuan/RuoYi-Vue3/commit/5d8172a11751c44212d3b784c122e1d0c6f10946)`https://github.com/yangzongzhuan/RuoYi-Vue3/commit/5d8172a11751c44212d3b784c122e1d0c6f10946`
