### ISSUE TITLE
Vue3 在Chrome浏览器中显示不完整，Chrom浏览器版本是72（32位）

### ISSUE THREAD

**Issue by Maipuhui-This** [yangzongzhuan/RuoYi-Vue3#295]
已在项目中增加了如下配置
vitePlugins.push(legacy({
        targets: ['defaults', 'not IE 11', 'chrome 48'],
    }))
但是打包后在浏览器中显示的情况效果如下
<img width="206" alt="image" src="https://github.com/user-attachments/assets/c959141d-87ed-4cdf-aee7-8d16765ff24e">
排查了动态路由的创建是结果是正常的。

**Comment by yangzongzhuan** [comment]
你提供详细的复现步骤和相关代码出来看一下 以及页面的截图，哪里显示不完整，这图并没有看出来。
