### ISSUE TITLE
vite开发vue3打包后，本地测试页面正常显示，部署到正式服务器上，打开页面却发现页面是空白的，刷新一下正常显示，退出重新登录又不正常了，只有个别用户出现问题

### ISSUE THREAD

**Issue by 22-wcx** [yangzongzhuan/RuoYi-Vue3#297]
vite开发vue3打包后，本地测试页面正常显示，部署到正式服务器上，打开页面却发现页面是空白的，刷新一下正常显示了，退出重新登录又不正常了，只有个别用户出现问题

**Comment by yangzongzhuan** [comment]
一般这种情况是template包含多个根元素，或注释放到`template`下，注意一级节点也包含注释，你放其他位置或把注释去掉即可。不然这样的话子组件就算有2个根元素，所以会导致页面空白，其他有类似问题的小伙伴也可以自己检查一下。

**正确示例** 
```
<script setup name="Config">
</script>

<template>
  <div>
     <!-- 添加或修改 对话框 -->
     6666
  </div>
</template>

<style scoped lang="scss">

</style>

```
