### ISSUE TITLE
vue3版本的《表单构建》显示不正确

### ISSUE THREAD

**Issue by xyjand** [yangzongzhuan/RuoYi-Vue3#30]
![image](https://user-images.githubusercontent.com/30721314/155934331-c8b1839c-d3dc-47d4-a13f-c331df37c814.png)

**Comment by zhuhaobam** [comment]
vue3压根就没有移植，况且这个是给OA流程用的，只有靠自己集成了。

**Comment by yangzongzhuan** [comment]
嗯，目前vue3版本没有表单构建功能。
