### ISSUE TITLE
DictTag存在bug，vue3已经不支持filter过滤器了

### ISSUE THREAD

**Issue by zhaokjun** [yangzongzhuan/RuoYi-Vue3#302]
当没字典表没匹配到时，显示的不是值。vue3已经没有了filter过滤器。

**Comment by yangzongzhuan** [comment]
// 是否当未找到匹配的数据时，显示原值value
`<dict-tag :options="sys_user_sex" :value="[1,2,3,4,5]" :show-value="false"></dict-tag>`
测试是正常的，没有问题，你看看是不是使用方式错了。
