### ISSUE TITLE
希望增加深色模式

### ISSUE THREAD

**Issue by yestarz** [yangzongzhuan/RuoYi-Vue3#303]
Element-Plus提供了深色模式，文档地址：https://cn.element-plus.org/zh-CN/guide/dark-mode.html

RuoYiVue-Plus实现了该功能。
在布局设置中提供深色模式选项：
![image](https://github.com/user-attachments/assets/36565e01-ff48-4b7b-aa00-8b9c58b4ce8a)
效果如下图：
![image](https://github.com/user-attachments/assets/98ef6b34-1b1f-4b8d-adf5-6f83c437c9b0)

**Comment by yangzongzhuan** [comment]
最新版本已经支持了，更新即可
