### ISSUE TITLE
vue3富文本刷新及表单验证问题

### ISSUE THREAD

**Issue by Mtouyao** [yangzongzhuan/RuoYi-Vue3#306]
当使用修改按钮时查询第一条信息，富文本框显示内容无误。
![image](https://github.com/user-attachments/assets/b84da061-5d4b-442a-8dcc-0914e0189175)

当再次点击第二条信息的修改时，富文本框会显示上一条信息的内容。（第二条的富文本框内容为null，不为空的情况下不不会引发此bug）
![image](https://github.com/user-attachments/assets/2ef23056-2b60-462d-b156-578a326c5dd2)

**Comment by Mtouyao** [comment]
富文本框的表单验证也不生效。
![image](https://github.com/user-attachments/assets/fa7ae7f7-1bec-44b5-b43a-c3adefdf1dab)
![image](https://github.com/user-attachments/assets/79331947-7879-4e85-8a16-f85603951185)

**Comment by zhujinrun** [comment]
Vue3富文本刷新问题解决方案：

修改  src\components\Editor\index.vue 文件第 111 行：
```
watch(() => props.modelValue, (v) => {
  if (v !== content.value) {
    content.value = v == undefined ? "<p></p>" : v; // 全等 `===` 改为  等于`==`
  }
}, { immediate: true });
```

**Comment by Mtouyao** [comment]
感谢！按照您的方法，问题已解决！😄

**Comment by elarbor** [comment]
这是vue3版的吗？

**Comment by zhujinrun** [comment]
> 这是vue3版的吗？

是的呀
