### ISSUE TITLE
rouyi-vue3在线构造器功能后续还会添加吗

### ISSUE THREAD

**Issue by qyxlyy** [yangzongzhuan/RuoYi-Vue3#307]
在线构造器，拖动表单元素生成相应的HTML代码。后续还会添加吗？

**Comment by COLrge** [comment]
同问

**Comment by yangzongzhuan** [comment]
已新增表单构建功能，更新代码即可。 [新增表单构建功能](https://github.com/yangzongzhuan/RuoYi-Vue3/commit/4db1eedc6a250b17397675f22274c7dde39bfc20)
`https://github.com/yangzongzhuan/RuoYi-Vue3/commit/4db1eedc6a250b17397675f22274c7dde39bfc20`
