### ISSUE TITLE
Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by wgy99024** [yangzongzhuan/RuoYi-Vue3#31]
故障现像:
 某个页面异常后 
点击所有正常页面都报错,
只能全部刷新

**Cannot read property 'parentNode' of null**

runtime-core.esm-bundler.js:6620 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next 
  at <RouterView> 
  at <AppMain> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>

<html>
<body>
<div tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(34, 34, 34); font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; white-space: pre-wrap; font-size: 12px !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(84, 84, 84); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">vue-router.esm-bundler.js:72</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(92, 60, 0);">[Vue Router warn]: uncaught error during route navigation:</span></span></div><div class="" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(34, 34, 34); font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: Consolas, &quot;Lucida Console&quot;, &quot;Courier New&quot;, monospace; font-size: 12px !important;">

  | warn | @ | vue-router.esm-bundler.js:72
-- | -- | -- | --
  | triggerError | @ | vue-router.esm-bundler.js:3293
  | (匿名) | @ | vue-router.esm-bundler.js:3334
  | Promise.catch(异步) |   |  
  | handleScroll | @ | vue-router.esm-bundler.js:3334
  | finalizeNavigation | @ | vue-router.esm-bundler.js:3188
  | (匿名) | @ | vue-router.esm-bundler.js:3060
  | Promise.then(异步) |   |  
  | pushWithRedirect | @ | vue-router.esm-bundler.js:3031
  | push | @ | vue-router.esm-bundler.js:2962
  | navigate | @ | vue-router.esm-bundler.js:2089
  | callWithErrorHandling | @ | runtime-core.esm-bundler.js:6737
  | callWithAsyncErrorHandling | @ | runtime-core.esm-bundler.js:6746
  | invoker | @ | runtime-dom.esm-bundler.js:357

</span></div>
</body>
</html>

**vue-router.esm-bundler.js:3295 TypeError: Cannot read property 'parentNode' of null**
    at parentNode (runtime-dom.esm-bundler.js:35)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4411)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6737)
    at flushJobs (runtime-core.esm-bundler.js:6976)

**runtime-dom.esm-bundler.js:35 Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null**
    at parentNode (runtime-dom.esm-bundler.js:35)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4411)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6737)
    at flushJobs (runtime-core.esm-bundler.js:6976)

**Comment by zhuhaobam** [comment]
建议全局搜索parentNode，并在代码前后打印东西，定位一下哪个写的不对

**Comment by yangzongzhuan** [comment]
相同的问题 https://gitee.com/y_project/RuoYi-Vue/issues/I4WRRH
