### ISSUE TITLE
login.vue中的ref watch等不引入就可以使用吗

### ISSUE THREAD

**Issue by newlearner1** [yangzongzhuan/RuoYi-Vue3#311]
login.vue中的ref watch useRoute useRouter这些不引入就可以使用吗？看代码里没有引入就直接用了

**Comment by xindeas** [comment]
有配置了自动引入，在vite/plugins/auto-import.js

**Comment by newlearner1** [comment]
> 有配置了自动引入，在vite/plugins/auto-import.js

好的，多谢

**Comment by yangzongzhuan** [comment]
楼上正解。
