### ISSUE TITLE
vue3 的前端页面运行首页显示不出来，如下图显示

### ISSUE THREAD

**Issue by xsf11** [yangzongzhuan/RuoYi-Vue3#312]
![11](https://github.com/user-attachments/assets/fdd2c5fe-d32b-45f0-9989-6847c808013a)

**Comment by xsf11** [comment]
前端：https://github.com/yangzongzhuan/RuoYi-Vue3   用的这个链接不行

**Comment by yangzongzhuan** [comment]
无法复现的问题，你这一看都不是ruoyi，跑错项目了，或者这个端口被占用了，跑的其他端口的应用。
