### ISSUE TITLE
打包部署后树形表格无法收缩

### ISSUE THREAD

**Issue by xindeas** [yangzongzhuan/RuoYi-Vue3#313]
以菜单管理为例，开发环境树形表格可以正常收缩展开，打包部署后发现不能收缩，按钮怎么点击都是展开状态，现推测是打包时element-plus的相关js出了什么问题，奈何技术有限，遂提出这个问题。
![image](https://github.com/user-attachments/assets/f14e11f1-92ec-47fd-897a-76da15917490)

**Comment by yangzongzhuan** [comment]
我本地和服务器用nginx部署后，树形表格都可以正常伸缩，没有你说的问题。
