### ISSUE TITLE
前端打包后所有路径404问题

### ISSUE THREAD

**Issue by kongxiyi** [yangzongzhuan/RuoYi-Vue3#34]
前端打包之后基本上所有项目都是404，值得注意的是我看了一下，暂时还没有网络请求，本地文件（css、js）首先就已经找不到了。求解决。

**Comment by Raywang80s** [comment]
打包问题，同求项目大佬指点一下。。

**Comment by Raywang80s** [comment]
> 前端打包之后基本上所有项目都是404，值得注意的是我看了一下，暂时还没有网络请求，本地文件（css、js）首先就已经找不到了。求解决。

打包问题，同求项目大佬指点一下。。

**Comment by Raywang80s** [comment]
打包问题，同求项目大佬指点。。。

**Comment by zhuhaobam** [comment]
请问你是npm run build:prod打包的吗，如果是，默认就这样

![image](https://user-images.githubusercontent.com/15319171/157401748-82d51fb1-3262-44d6-a363-5488c57e7cfd.png)

![image](https://user-images.githubusercontent.com/15319171/157401806-5e920101-13e4-4be7-a35c-174fe9bb7b99.png)

**Comment by zhuhaobam** [comment]
dev命令下面那个prod命令我是改了点，这个主要是启动就用prod，免得打包还要改代理那里，其他的是没啥变化。还有我nginx配置的就是根文件index.html,没有加什么其他的多级路由，如果是history模式的话，nginx还要加上重定向到当前路由（history模式现需要注意的）

**Comment by zhuhaobam** [comment]
![image](https://user-images.githubusercontent.com/15319171/157404251-9e26b3e9-2663-467c-823e-cd8c94d43c29.png)

**Comment by zhuhaobam** [comment]
`location /prod-api/profile/  {
		  proxy_set_header Host $http_host;
    		proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header REMOTE-HOST $remote_addr;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_pass http://127.0.0.1:7590/profile/;
		}
    
     location /prod-api/ {
    		proxy_set_header Host $http_host;
    		proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header REMOTE-HOST $remote_addr;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_pass http://127.0.0.1:7590/;
		}`

**Comment by yangzongzhuan** [comment]
参考文档配置 http://doc.ruoyi.vip/ruoyi-vue/document/hjbs.html#nginx配置

**Comment by guomengf** [comment]
通过yarn build:stage 命令构建完成之后，把dist文件放到后端代码里部署到服务器上，访问我的ip:8080/index.html，报"status":404,"error":"Not Found","path":"/stage-api/captchaImage"，这个stage-api为啥没有替换掉了
