### ISSUE TITLE
TopNav默认看板页面显示不协调

### ISSUE THREAD

**Issue by zhuhaobam** [yangzongzhuan/RuoYi-Vue3#35]
1.默认进入首页看板，头部导航栏靠右，且左边空白【固定顶部导航栏】。
2.处理方式进如components/TopNav/index.vue 文件
![image](https://user-images.githubusercontent.com/15319171/157398897-7a456e2d-73b7-4f83-9c92-2a2ee50cbb90.png)
*将此处的true改为false。
![image](https://user-images.githubusercontent.com/15319171/157399021-b50ae1be-d667-4c8c-973f-ad1581c6097a.png)
*这里/index由于上面的处理，所以吧斜杠的情况也加入进来。
此处的index来源于路由中的配置，请检查你自己的是否匹配

**Comment by yangzongzhuan** [comment]
相同的问题，已做修复。 https://gitee.com/y_project/RuoYi-Vue/issues/I4XDN5
