### ISSUE TITLE
代码生成是不是没有vue3的模板啊

### ISSUE THREAD

**Issue by WuWenL0** [yangzongzhuan/RuoYi-Vue3#4]
rt

**Comment by yaolunmao** [comment]
我也发现了 生成的是vue2版本的 而且vue3的dict获取和vue2不一样了

**Comment by yangzongzhuan** [comment]
已经支持了，覆盖一下v3目录即可。
[新增Vue3前端代码生成模板](https://gitee.com/y_project/RuoYi-Vue/commit/fef7ead0d5e7fc94b62662997f806898100fc6ef)
`https://gitee.com/y_project/RuoYi-Vue/commit/fef7ead0d5e7fc94b62662997f806898100fc6ef`
