### ISSUE TITLE
服务器启动起来后，第一次能访问，点刷新报404

### ISSUE THREAD

**Issue by majiang26** [yangzongzhuan/RuoYi-Vue3#45]
![_ANX)(~8C_@WA```G~QU}P4](https://user-images.githubusercontent.com/40787520/162567274-c87b2417-076b-4f38-add0-86a8c2ed724c.png)

![1`HU1D28 UQ2`U4XMOWR3SW](https://user-images.githubusercontent.com/40787520/162567347-aac50e36-5366-4a76-acfe-07a0823d5959.png)

**Comment by yangzongzhuan** [comment]
参考文档 http://doc.ruoyi.vip/ruoyi-vue/document/hjbs.html#tomcat配置
