### ISSUE TITLE
路由跳转后返回上个页面，页面空白无法显示

### ISSUE THREAD

**Issue by Xuxianhai** [yangzongzhuan/RuoYi-Vue3#50]
路由跳转后返回上个页面，页面空白无法显示
![image](https://user-images.githubusercontent.com/52366516/164439749-099b9de1-aef4-484f-90b6-e4f7f51fd59d.png)

**Comment by yangzongzhuan** [comment]
请提供出能复现问题的详细步骤

**Comment by Xuxianhai** [comment]
页面通过![image](https://user-images.githubusercontent.com/52366516/165691377-2934ada5-06b1-4b58-8c19-8d0b3eb7d0d4.png)跳转页面进入详情页后点击返回通过
![image](https://user-images.githubusercontent.com/52366516/165691979-8d7aeba3-4e8f-436f-a8fe-791207cb0ae6.png)
返回上一页页面呈现空白页面然后点击其他页面也是空白页面

**Comment by html9527** [comment]
你好,请问这个问题您解决了吗?我这边也是出现了 这种情况

**Comment by Xuxianhai** [comment]
> 你好，请问这个问题你解决了吗？我这也是出现了这种情况
![image](https://user-images.githubusercontent.com/52366516/177675813-73bc6279-c377-4ab1-955a-a3f39fbdf222.png)
在这里加个key就好了改成route.path

**Comment by html9527** [comment]
感谢
