### ISSUE TITLE
验证码加载不出来

### ISSUE THREAD

**Issue by missyang-123** [yangzongzhuan/RuoYi-Vue3#51]
下载完依赖，yarn dev  跑起来访问地址是：http://localhost:8080/dev-api

请问：我在哪里修改请求访问的baseURL：http://vue.ruoyi.vip/prod-api

现在baseURL的访问地址是： （util的request文件）baseURL: import.meta.env.VITE_APP_BASE_API, 怎么修改呢

**Comment by missyang-123** [comment]
我好像解决问题了，直接将http://vue.ruoyi.vip/prod-api 复制到baseURL后面，问题解决了，但是这个解决方式肯定是与作者的思路是不一致的，baseURL: import.meta.env.VITE_APP_BASE_API，这个是什么意思，怎么处理啊

**Comment by yangzongzhuan** [comment]
域名是要自己注册配置的，你本地做不到。`VITE_APP_BASE_API`就是配置的prod-api
