### ISSUE TITLE
设置主题颜色失败

### ISSUE THREAD

**Issue by DDQH** [yangzongzhuan/RuoYi-Vue3#52]
修改主题颜色，只有侧边栏被修改了，其他按钮等控件颜色都没改变

**Comment by aqaaqa** [comment]
22.5.31下载最新的项目也有这个问题，求解决办法，感觉应该是少安装了什么东西
![image](https://user-images.githubusercontent.com/20698629/171124331-1b19fb6c-e02d-494d-8d69-592e4d877465.png)

**Comment by iminhw** [comment]
我也是碰到了这个问题 需要修复，

**Comment by yanghubin** [comment]
me too.目前看demo是可以的，http://vue.ruoyi.vip/，怎么修改呢？

**Comment by yanghubin** [comment]
已解决，在src/layout/index.vue文件里面，添加这个--el-color-primary变量即可解决。
![image](https://user-images.githubusercontent.com/24384461/179916045-96112c0c-8b36-41d2-83fe-8b4fd623c29f.png)

**Comment by iminhw** [comment]
demo 是vue2的版本，不是vue3



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 下午2:24
收件人: "yangzongzhuan/RuoYi-Vue3";
抄送: "Comment";
主题: Re: [yangzongzhuan/RuoYi-Vue3] 设置主题颜色失败 (Issue #52)





 
me too.目前看demo是可以的，http://vue.ruoyi.vip/，怎么修改呢？
 
&mdash;

**Comment by yanghubin** [comment]
> demo 是vue2的版本，不是vue3
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月20日(星期三) 下午2:24 收件人: "yangzongzhuan/RuoYi-Vue3"; 抄送: "Comment"; 主题: Re: [yangzongzhuan/RuoYi-Vue3] 设置主题颜色失败 (Issue #52) me too.目前看demo是可以的，[http://vue.ruoyi.vip/，怎么修改呢？](http://vue.ruoyi.vip/%EF%BC%8C%E6%80%8E%E4%B9%88%E4%BF%AE%E6%94%B9%E5%91%A2%EF%BC%9F) &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我使用的是vue3,并且按照上面这样修改已解决

**Comment by yangzongzhuan** [comment]
已经支持，更新最新的代码即可。[支持全局主题颜色设置](https://github.com/yangzongzhuan/RuoYi-Vue3/commit/f8e64316848ab390ddc550eea81e45e604ade500)
`https://github.com/yangzongzhuan/RuoYi-Vue3/commit/f8e64316848ab390ddc550eea81e45e604ade500`
