### ISSUE TITLE
通知公告怎么没有把富文本编辑器加上

### ISSUE THREAD

**Issue by cschenzz** [yangzongzhuan/RuoYi-Vue3#55]
vue2版本的有这功能, vue3的怎么没有把这功能加上, 这功能还是很需要

**Comment by vincecarterhu** [comment]
加一 vue3用2的版本各种报错还望大佬解决下

**Comment by yangzongzhuan** [comment]
目前还没有计划， 这个有需要可以自己去集成 以下两款的可以，也有提供示例
vue3-quill  https://flyween.github.io/vue3-quill/
tinymce     http://tinymce.ax-z.cn/
