### ISSUE TITLE
字典问题 

### ISSUE THREAD

**Issue by cwjhome** [yangzongzhuan/RuoYi-Vue3#63]
手册上这样写
import DictData from '@/components/DictData'
DictData.install()

说这个在main.js里面有 
但是看下了没有 生成的模板有关联字典就报错

**Comment by cwjhome** [comment]
用的最新的3.8.2版本

**Comment by hongbinhsu** [comment]
@/components/DictData
Vue3 版本中缺少了这个组件，github与gitee是并不一样

**Comment by yangzongzhuan** [comment]
vue3版本使用方式不一样，没有install 而是通过useDict读取，参考示例。
const { sys_yes_no } = proxy.useDict("sys_yes_no");
