### ISSUE TITLE
打包发布后时不时会出现加载全白的情况，查询发现是是多的这个文件导致

### ISSUE THREAD

**Issue by iminhw** [yangzongzhuan/RuoYi-Vue3#65]
<img width="944" alt="截屏2022-06-26 03 34 01" src="https://user-images.githubusercontent.com/55385744/175788187-67998a9c-90d0-4240-adbd-cd82ded3172d.png">

多出来的地址
https://res.iyoowi.com/iy/iy.js?cid=0E8B27F0&apmac=0c:ef:af:b1:d8:7b&mac=a4:83:e7:51:df:e6&rid=414098

**Comment by yangzongzhuan** [comment]
项目里面没有调用第三方地址，检查是不是自己依赖其他的插件导致的。
