### ISSUE TITLE
注册开启后，登陆页面不会展示注册入口，直接访问register可以填写信息课正常注册帐号，

### ISSUE THREAD

**Issue by iminhw** [yangzongzhuan/RuoYi-Vue3#66]

**Comment by iminhw** [comment]
新注册帐号拥有所有权限！！！！

**Comment by biuhe** [comment]
我发现了是vue3版本没加载配置项，vue2 版本中是包含的。
类似这个初始密码
<img width="597" alt="image" src="https://user-images.githubusercontent.com/14000394/197373474-edb5ceac-bf9f-48db-a547-7b6591d2ada9.png">

**Comment by yangzongzhuan** [comment]
参考文档 http://doc.ruoyi.vip/ruoyi-vue/other/faq.html#登录页如何开启注册用户功能

vue版本 login.vue register属性开关需要设置为true
