### ISSUE TITLE
调试debugger行位置不对

### ISSUE THREAD

**Issue by hnldx** [yangzongzhuan/RuoYi-Vue3#67]
调试debugger行时，浏览器所停的行位置不对

**Comment by shaokunpeng** [comment]
有解决办法吗，我也遇到了

**Comment by hnldx** [comment]
不用 vite-plugin-vue-setup-extend，我是直接将vite/plugins/index.js里面的 vitePlugins.push(createSetupExtend()) 删除

**Comment by yangzongzhuan** [comment]
这个是方便匹配路由name的，会导致调试一些不方便的问题，可以去掉`vite-plugin-vue-setup-extend`插件。
去掉这个插件路由缓存的`name`得这样写、
```
<script>
  export default {
    name: 'User',
  }
</script>

<script setup>
  // script setup logic
</script>

而不是`<script setup name="User">`
```

**Comment by hnldx** [comment]
好的谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月30日(星期六) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangzongzhuan/RuoYi-Vue3] 调试debugger行位置不对 (Issue #67)





 
这个是方便匹配路由name的，会导致调试一些不方便的问题，可以去掉vite-plugin-vue-setup-extend插件。
 去掉这个插件路由缓存的name得这样写、
 <script&gt;   export default {     name: 'User',   } </script&gt; <script setup&gt;   // script setup logic </script&gt; 而不是`<script setup name="User"&gt;`
