### ISSUE TITLE
sourcemap 有问题，控制台无显示源码

### ISSUE THREAD

**Issue by dream-ty** [yangzongzhuan/RuoYi-Vue3#7]
![GG)B@4W(B9X ~Z$D692CW$V](https://user-images.githubusercontent.com/42374447/147640566-d1854984-a997-48e2-95a1-9d331539c747.png)
![@ 0N_RDBDNPPC%3I~M22G1Y](https://user-images.githubusercontent.com/42374447/147640570-d5a610e4-c093-4e0f-a339-4b9c47a8bd86.png)

**Comment by yangzongzhuan** [comment]
需要提供出能复现问题的详细步骤。

**Comment by dream-ty** [comment]
https://gitee.com/y_project/RuoYi-Vue/issues/I4OLJ0    详细的
