### ISSUE TITLE
这个vue3 版本的代码生成功能只能生成vue2的吗？

### ISSUE THREAD

**Issue by Manitesto** [yangzongzhuan/RuoYi-Vue3#72]

**Comment by wangyanbin110** [comment]
同样的问题

**Comment by ycn15013714719** [comment]
需要在后端进行修改，前端默认还是生成el3.0之前的版本。

**Comment by ycn15013714719** [comment]
需要在后端进行修改，前端默认还是生成el3.0之前的版本。 修改ruoyi-gen模块的com.ruoyi.gen.util.VelocityUtils，getTemplateList方法获取模版信息中vm/vue/index.vue.vm修改成vm/vue/v3/index.vue.vm，这些模版文件都在resource/vm里面，把几个都改一下服务重启一下就可以了

**Comment by yangzongzhuan** [comment]
都支持，需要修改一下后端。把vue3的模板覆盖到vm目录。
这里有说明 https://gitee.com/y_project/RuoYi-Vue/blob/master/ruoyi-generator/src/main/resources/vm/vue/v3/readme.txt

**Comment by wangyanbin110** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wangyanbin110** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
