### ISSUE TITLE
升级后菜单按钮切换不记载

### ISSUE THREAD

**Issue by lqmxiaogang** [yangzongzhuan/RuoYi-Vue3#78]
[git重新垃取后菜单按钮切换不记载
<img width="1450" alt="WX20220803-130845@2x" src="https://user-images.githubusercontent.com/9531627/182528858-16bbd430-0955-452b-b37f-fee15281f125.png">
,

**Comment by yangzongzhuan** [comment]
测试验证是有效的，没有你说的问题, 请提供出能复现问题详细描述和步骤。
