### ISSUE TITLE
mac 无法运行 怎么解决 急！！！

### ISSUE THREAD

**Issue by LeungWinly** [yangzongzhuan/RuoYi-Vue3#82]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/26197079/183965168-0f1dbe79-a074-4a9b-9f17-fb5bb6664aa1.png">

**Comment by phpYida** [comment]
要连接后端端口的才能运行

**Comment by zilongzixue** [comment]
看乐了，楼上是天才

**Comment by yangzongzhuan** [comment]
看错误是8080端口连接不上，而这个端口需要去启动后端代码（ruoyi-vue），你可以去下载启动再试。

https://gitee.com/y_project/RuoYi-Vue
