### ISSUE TITLE
菜单修改时图标选择的搜索框无法输入

### ISSUE THREAD

**Issue by jinkunaier** [yangzongzhuan/RuoYi-Vue3#85]
菜单修改时图标选择的搜索框无法输入

**Comment by 453629963** [comment]
升级element-plus版本到2.2.15以上可以解决这个问题。升级后会出现另一个问题就是菜单选择弹框一打开就会消失，把

**Comment by yangzongzhuan** [comment]
测试是正常的，没有问题，你重新拉取最新的版本试试看。
![输入图片说明](https://foruda.gitee.com/images/1668649607161145599/0b4acbb7_1151004.png "屏幕截图")
