### ISSUE TITLE
在拥有缓存功能的组件中无法使用热更新,只要改变代码就会报错

### ISSUE THREAD

**Issue by mfxhb** [yangzongzhuan/RuoYi-Vue3#89]
![image](https://user-images.githubusercontent.com/82220999/187388378-564972ed-dd9b-4fbb-82cb-6952e0f31141.png)

我在gitee上面提到的问题的 <https://gitee.com/y_project/RuoYi/issues/I5OTS5#note_12729974>

我试了,系统菜单中使用打印也会报错,在没有缓存功能的组件当中就没事,

![image](https://user-images.githubusercontent.com/82220999/187388739-416cc3b0-e5dd-4f49-a73c-571b604231d7.png)

**Comment by LHR703** [comment]
这个问题我也遇到了 vue官方都没修复好https://github.com/vuejs/core/issues/6222

**Comment by chenhaihong** [comment]
建议给个最小复现代码。

**Comment by leyue** [comment]
@chenhaihong 使用低版本的浏览器会出现这个问题

**Comment by xjtarzan** [comment]
我也是这样，热更新就报错

**Comment by yangzongzhuan** [comment]
测试验证带缓存使用热更新是正常的，你可以提供出示例DEMO出来看一下。
