### ISSUE TITLE
vue3.0的生成代码模板

### ISSUE THREAD

**Issue by wbgalaxy** [yangzongzhuan/RuoYi-Vue3#9]
ruoyi-vue3.0的生成代码模板VM文件什么时候更新

**Comment by yangzongzhuan** [comment]
3.8.1版本已经有了。覆盖一下此目录的模板index.vue.vm、index-tree.vue.vm文件到上级vue目录。
https://gitee.com/y_project/RuoYi-Vue/tree/master/ruoyi-generator/src/main/resources/vm/vue/v3
