### ISSUE TITLE
svgIcon组件无法修改SVG的颜色

### ISSUE THREAD

**Issue by 453629963** [yangzongzhuan/RuoYi-Vue3#90]
在给svgIcon组件的color赋值时发现不生效。
我直接在组件内把fill写死也不起作用，我查看了SVG文件，其中没有写死fill的地方。
请问这个问题是什么情况

**Comment by lionHua** [comment]
fill 属性去掉。color修改呢

**Comment by yangzongzhuan** [comment]
你参考这个PR试试 
https://github.com/yangzongzhuan/RuoYi-Vue3/commit/dccb755ae3d5103537e283ff597319ac8129d8f5
