### ISSUE TITLE
el-dialog关闭问题

### ISSUE THREAD

**Issue by kuku1166** [yangzongzhuan/RuoYi-Vue3#92]
el-dialog点击保存v-model值变成false了但弹窗并没有关闭，同时再次点击保存控制台报错，此时无论点弹窗上的×还是点击弹窗外部都无法关闭弹窗。这种情况也是偶尔才出现，大多数时候弹窗还是会关闭的，有人遇到过吗？

**Comment by kuku1166** [comment]
![图片](https://user-images.githubusercontent.com/53868294/188416373-9d531339-c1fb-4927-9f58-72d1f772f73d.png)
![图片](https://user-images.githubusercontent.com/53868294/188416442-8594aac2-2438-4a42-931d-027587e9ca7c.png)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题步骤和示例DEMO。
