### ISSUE TITLE
war包无法按文档打包

### ISSUE THREAD

**Issue by mangdehuang** [yangzongzhuan/RuoYi-Vue3#94]
安装文档提示 改成war  打war包  提示报错

**Comment by mangdehuang** [comment]
![image](https://user-images.githubusercontent.com/10792335/189025124-1c4348da-a7e0-4e4e-850e-945e5c941ae7.png)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题步骤。
