### ISSUE TITLE
TreeSelect组件无法显示清空按钮

### ISSUE THREAD

**Issue by shaokuuipo** [yangzongzhuan/RuoYi-Vue3#96]

**Comment by cuixin3266** [comment]
看element plus[官方文档 ](https://element-plus.org/zh-CN/component/tree-select.html#treeselect-%E5%B1%9E%E6%80%A7)这里有提及，TreeSelect是由`el-tree`和`el-select`的结合体，要清空，直接使用`el-select`的`clearable`属性
