### ISSUE TITLE
前端萌新请：浏览器控制台调试显示源码为什么和vue文件不匹配？

### ISSUE THREAD

**Issue by bantu4me** [yangzongzhuan/RuoYi-Vue3#98]
如题：现象如下图。。这样的话，没办法调试啊。网上找了好久，可能关键词描述不对，都是关于vite项目源码的。。希望大佬帮忙解答下，或告知相关技术关键字。。
![image](https://user-images.githubusercontent.com/11781345/192104614-9f44e4f9-2cd4-4e1e-a505-d25ad1185abb.png)
![image](https://user-images.githubusercontent.com/11781345/192104643-f945a362-9b49-477f-892f-6a83741e2d3b.png)

**Comment by bantu4me** [comment]
https://gitee.com/y_project/RuoYi-Vue/issues/I4OLJ0
参考这个，是vite-plugin-vue-setup-extend这个插件的问题吗？

**Comment by junlin365** [comment]
[unplugin-vue-setup-extend-plus](https://www.npmjs.com/package/unplugin-vue-setup-extend-plus)
可以试试这个，我的项目改用这个插件后没这个问题了

**Comment by yangzongzhuan** [comment]
楼上小伙伴的方案都可以试试，
1、去掉这个插件vite-plugin-vue-setup-extend 
2、更换成unplugin-vue-setup-extend-plus
