### ISSUE TITLE
当页面只有一个输入框时，按回车会相当于F5刷新

### ISSUE THREAD

**Issue by Ainlray** [yangzongzhuan/RuoYi-Vue3#99]
当页面上只有1个输入框时按回车相当于F5刷新，拥有至少2个输入框时才会正常调用@keyup.enter="handleQuery"刷新列表

**Comment by Japheth1989** [comment]
在form表单上加 @submit.native.prevent 事件

**Comment by Montaro2017** [comment]
https://element-plus.gitee.io/zh-CN/component/form.html#%E5%85%B8%E5%9E%8B%E8%A1%A8%E5%8D%95

![image](https://user-images.githubusercontent.com/35142778/199865487-6a286c1e-c5e8-4146-b909-91dd8647b0c2.png)

**Comment by yangzongzhuan** [comment]
楼上正解，这个element ui 和 element plus 都是一样的操作。

参考文档  http://doc.ruoyi.vip/ruoyi-vue/other/faq.html#表单按回车键会刷新页面问题
